// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// AccountLockRule is an object representing the database table.
type AccountLockRule struct {
	ID            string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	AccountID     string    `boil:"account_id" json:"account_id" toml:"account_id" yaml:"account_id"`
	AccountStatus string    `boil:"account_status" json:"account_status" toml:"account_status" yaml:"account_status"`
	FieldName     string    `boil:"field_name" json:"field_name" toml:"field_name" yaml:"field_name"`
	LockType      string    `boil:"lock_type" json:"lock_type" toml:"lock_type" yaml:"lock_type"`
	LockReason    string    `boil:"lock_reason" json:"lock_reason" toml:"lock_reason" yaml:"lock_reason"`
	CreatedAt     time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt     time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *accountLockRuleR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L accountLockRuleL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AccountLockRuleColumns = struct {
	ID            string
	AccountID     string
	AccountStatus string
	FieldName     string
	LockType      string
	LockReason    string
	CreatedAt     string
	UpdatedAt     string
}{
	ID:            "id",
	AccountID:     "account_id",
	AccountStatus: "account_status",
	FieldName:     "field_name",
	LockType:      "lock_type",
	LockReason:    "lock_reason",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
}

var AccountLockRuleTableColumns = struct {
	ID            string
	AccountID     string
	AccountStatus string
	FieldName     string
	LockType      string
	LockReason    string
	CreatedAt     string
	UpdatedAt     string
}{
	ID:            "account_lock_rules.id",
	AccountID:     "account_lock_rules.account_id",
	AccountStatus: "account_lock_rules.account_status",
	FieldName:     "account_lock_rules.field_name",
	LockType:      "account_lock_rules.lock_type",
	LockReason:    "account_lock_rules.lock_reason",
	CreatedAt:     "account_lock_rules.created_at",
	UpdatedAt:     "account_lock_rules.updated_at",
}

// Generated where

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var AccountLockRuleWhere = struct {
	ID            whereHelperstring
	AccountID     whereHelperstring
	AccountStatus whereHelperstring
	FieldName     whereHelperstring
	LockType      whereHelperstring
	LockReason    whereHelperstring
	CreatedAt     whereHelpertime_Time
	UpdatedAt     whereHelpertime_Time
}{
	ID:            whereHelperstring{field: "\"account_lock_rules\".\"id\""},
	AccountID:     whereHelperstring{field: "\"account_lock_rules\".\"account_id\""},
	AccountStatus: whereHelperstring{field: "\"account_lock_rules\".\"account_status\""},
	FieldName:     whereHelperstring{field: "\"account_lock_rules\".\"field_name\""},
	LockType:      whereHelperstring{field: "\"account_lock_rules\".\"lock_type\""},
	LockReason:    whereHelperstring{field: "\"account_lock_rules\".\"lock_reason\""},
	CreatedAt:     whereHelpertime_Time{field: "\"account_lock_rules\".\"created_at\""},
	UpdatedAt:     whereHelpertime_Time{field: "\"account_lock_rules\".\"updated_at\""},
}

// AccountLockRuleRels is where relationship names are stored.
var AccountLockRuleRels = struct {
	Account string
}{
	Account: "Account",
}

// accountLockRuleR is where relationships are stored.
type accountLockRuleR struct {
	Account *Account `boil:"Account" json:"Account" toml:"Account" yaml:"Account"`
}

// NewStruct creates a new relationship struct
func (*accountLockRuleR) NewStruct() *accountLockRuleR {
	return &accountLockRuleR{}
}

func (o *AccountLockRule) GetAccount() *Account {
	if o == nil {
		return nil
	}

	return o.R.GetAccount()
}

func (r *accountLockRuleR) GetAccount() *Account {
	if r == nil {
		return nil
	}

	return r.Account
}

// accountLockRuleL is where Load methods for each relationship are stored.
type accountLockRuleL struct{}

var (
	accountLockRuleAllColumns            = []string{"id", "account_id", "account_status", "field_name", "lock_type", "lock_reason", "created_at", "updated_at"}
	accountLockRuleColumnsWithoutDefault = []string{"id", "account_id", "account_status", "field_name", "lock_reason"}
	accountLockRuleColumnsWithDefault    = []string{"lock_type", "created_at", "updated_at"}
	accountLockRulePrimaryKeyColumns     = []string{"id"}
	accountLockRuleGeneratedColumns      = []string{}
)

type (
	// AccountLockRuleSlice is an alias for a slice of pointers to AccountLockRule.
	// This should almost always be used instead of []AccountLockRule.
	AccountLockRuleSlice []*AccountLockRule
	// AccountLockRuleHook is the signature for custom AccountLockRule hook methods
	AccountLockRuleHook func(context.Context, boil.ContextExecutor, *AccountLockRule) error

	accountLockRuleQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	accountLockRuleType                 = reflect.TypeOf(&AccountLockRule{})
	accountLockRuleMapping              = queries.MakeStructMapping(accountLockRuleType)
	accountLockRulePrimaryKeyMapping, _ = queries.BindMapping(accountLockRuleType, accountLockRuleMapping, accountLockRulePrimaryKeyColumns)
	accountLockRuleInsertCacheMut       sync.RWMutex
	accountLockRuleInsertCache          = make(map[string]insertCache)
	accountLockRuleUpdateCacheMut       sync.RWMutex
	accountLockRuleUpdateCache          = make(map[string]updateCache)
	accountLockRuleUpsertCacheMut       sync.RWMutex
	accountLockRuleUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var accountLockRuleAfterSelectMu sync.Mutex
var accountLockRuleAfterSelectHooks []AccountLockRuleHook

var accountLockRuleBeforeInsertMu sync.Mutex
var accountLockRuleBeforeInsertHooks []AccountLockRuleHook
var accountLockRuleAfterInsertMu sync.Mutex
var accountLockRuleAfterInsertHooks []AccountLockRuleHook

var accountLockRuleBeforeUpdateMu sync.Mutex
var accountLockRuleBeforeUpdateHooks []AccountLockRuleHook
var accountLockRuleAfterUpdateMu sync.Mutex
var accountLockRuleAfterUpdateHooks []AccountLockRuleHook

var accountLockRuleBeforeDeleteMu sync.Mutex
var accountLockRuleBeforeDeleteHooks []AccountLockRuleHook
var accountLockRuleAfterDeleteMu sync.Mutex
var accountLockRuleAfterDeleteHooks []AccountLockRuleHook

var accountLockRuleBeforeUpsertMu sync.Mutex
var accountLockRuleBeforeUpsertHooks []AccountLockRuleHook
var accountLockRuleAfterUpsertMu sync.Mutex
var accountLockRuleAfterUpsertHooks []AccountLockRuleHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AccountLockRule) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountLockRuleAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AccountLockRule) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountLockRuleBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AccountLockRule) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountLockRuleAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AccountLockRule) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountLockRuleBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AccountLockRule) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountLockRuleAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AccountLockRule) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountLockRuleBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AccountLockRule) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountLockRuleAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AccountLockRule) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountLockRuleBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AccountLockRule) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountLockRuleAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAccountLockRuleHook registers your hook function for all future operations.
func AddAccountLockRuleHook(hookPoint boil.HookPoint, accountLockRuleHook AccountLockRuleHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		accountLockRuleAfterSelectMu.Lock()
		accountLockRuleAfterSelectHooks = append(accountLockRuleAfterSelectHooks, accountLockRuleHook)
		accountLockRuleAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		accountLockRuleBeforeInsertMu.Lock()
		accountLockRuleBeforeInsertHooks = append(accountLockRuleBeforeInsertHooks, accountLockRuleHook)
		accountLockRuleBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		accountLockRuleAfterInsertMu.Lock()
		accountLockRuleAfterInsertHooks = append(accountLockRuleAfterInsertHooks, accountLockRuleHook)
		accountLockRuleAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		accountLockRuleBeforeUpdateMu.Lock()
		accountLockRuleBeforeUpdateHooks = append(accountLockRuleBeforeUpdateHooks, accountLockRuleHook)
		accountLockRuleBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		accountLockRuleAfterUpdateMu.Lock()
		accountLockRuleAfterUpdateHooks = append(accountLockRuleAfterUpdateHooks, accountLockRuleHook)
		accountLockRuleAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		accountLockRuleBeforeDeleteMu.Lock()
		accountLockRuleBeforeDeleteHooks = append(accountLockRuleBeforeDeleteHooks, accountLockRuleHook)
		accountLockRuleBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		accountLockRuleAfterDeleteMu.Lock()
		accountLockRuleAfterDeleteHooks = append(accountLockRuleAfterDeleteHooks, accountLockRuleHook)
		accountLockRuleAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		accountLockRuleBeforeUpsertMu.Lock()
		accountLockRuleBeforeUpsertHooks = append(accountLockRuleBeforeUpsertHooks, accountLockRuleHook)
		accountLockRuleBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		accountLockRuleAfterUpsertMu.Lock()
		accountLockRuleAfterUpsertHooks = append(accountLockRuleAfterUpsertHooks, accountLockRuleHook)
		accountLockRuleAfterUpsertMu.Unlock()
	}
}

// One returns a single accountLockRule record from the query.
func (q accountLockRuleQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AccountLockRule, error) {
	o := &AccountLockRule{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: failed to execute a one query for account_lock_rules")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all AccountLockRule records from the query.
func (q accountLockRuleQuery) All(ctx context.Context, exec boil.ContextExecutor) (AccountLockRuleSlice, error) {
	var o []*AccountLockRule

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbmodels: failed to assign all query results to AccountLockRule slice")
	}

	if len(accountLockRuleAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all AccountLockRule records in the query.
func (q accountLockRuleQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to count account_lock_rules rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q accountLockRuleQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: failed to check if account_lock_rules exists")
	}

	return count > 0, nil
}

// Account pointed to by the foreign key.
func (o *AccountLockRule) Account(mods ...qm.QueryMod) accountQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.AccountID),
	}

	queryMods = append(queryMods, mods...)

	return Accounts(queryMods...)
}

// LoadAccount allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (accountLockRuleL) LoadAccount(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAccountLockRule interface{}, mods queries.Applicator) error {
	var slice []*AccountLockRule
	var object *AccountLockRule

	if singular {
		var ok bool
		object, ok = maybeAccountLockRule.(*AccountLockRule)
		if !ok {
			object = new(AccountLockRule)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAccountLockRule)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAccountLockRule))
			}
		}
	} else {
		s, ok := maybeAccountLockRule.(*[]*AccountLockRule)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAccountLockRule)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAccountLockRule))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &accountLockRuleR{}
		}
		args[object.AccountID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &accountLockRuleR{}
			}

			args[obj.AccountID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`accounts`),
		qm.WhereIn(`accounts.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Account")
	}

	var resultSlice []*Account
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Account")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for accounts")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for accounts")
	}

	if len(accountAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Account = foreign
		if foreign.R == nil {
			foreign.R = &accountR{}
		}
		foreign.R.AccountLockRules = append(foreign.R.AccountLockRules, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.AccountID == foreign.ID {
				local.R.Account = foreign
				if foreign.R == nil {
					foreign.R = &accountR{}
				}
				foreign.R.AccountLockRules = append(foreign.R.AccountLockRules, local)
				break
			}
		}
	}

	return nil
}

// SetAccount of the accountLockRule to the related item.
// Sets o.R.Account to related.
// Adds o to related.R.AccountLockRules.
func (o *AccountLockRule) SetAccount(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Account) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"account_lock_rules\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"account_id"}),
		strmangle.WhereClause("\"", "\"", 2, accountLockRulePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.AccountID = related.ID
	if o.R == nil {
		o.R = &accountLockRuleR{
			Account: related,
		}
	} else {
		o.R.Account = related
	}

	if related.R == nil {
		related.R = &accountR{
			AccountLockRules: AccountLockRuleSlice{o},
		}
	} else {
		related.R.AccountLockRules = append(related.R.AccountLockRules, o)
	}

	return nil
}

// AccountLockRules retrieves all the records using an executor.
func AccountLockRules(mods ...qm.QueryMod) accountLockRuleQuery {
	mods = append(mods, qm.From("\"account_lock_rules\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"account_lock_rules\".*"})
	}

	return accountLockRuleQuery{q}
}

// FindAccountLockRule retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAccountLockRule(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*AccountLockRule, error) {
	accountLockRuleObj := &AccountLockRule{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"account_lock_rules\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, accountLockRuleObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: unable to select from account_lock_rules")
	}

	if err = accountLockRuleObj.doAfterSelectHooks(ctx, exec); err != nil {
		return accountLockRuleObj, err
	}

	return accountLockRuleObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AccountLockRule) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodels: no account_lock_rules provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(accountLockRuleColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	accountLockRuleInsertCacheMut.RLock()
	cache, cached := accountLockRuleInsertCache[key]
	accountLockRuleInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			accountLockRuleAllColumns,
			accountLockRuleColumnsWithDefault,
			accountLockRuleColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(accountLockRuleType, accountLockRuleMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(accountLockRuleType, accountLockRuleMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"account_lock_rules\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"account_lock_rules\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to insert into account_lock_rules")
	}

	if !cached {
		accountLockRuleInsertCacheMut.Lock()
		accountLockRuleInsertCache[key] = cache
		accountLockRuleInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the AccountLockRule.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AccountLockRule) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	accountLockRuleUpdateCacheMut.RLock()
	cache, cached := accountLockRuleUpdateCache[key]
	accountLockRuleUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			accountLockRuleAllColumns,
			accountLockRulePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbmodels: unable to update account_lock_rules, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"account_lock_rules\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, accountLockRulePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(accountLockRuleType, accountLockRuleMapping, append(wl, accountLockRulePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update account_lock_rules row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by update for account_lock_rules")
	}

	if !cached {
		accountLockRuleUpdateCacheMut.Lock()
		accountLockRuleUpdateCache[key] = cache
		accountLockRuleUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q accountLockRuleQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all for account_lock_rules")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected for account_lock_rules")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AccountLockRuleSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbmodels: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountLockRulePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"account_lock_rules\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, accountLockRulePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all in accountLockRule slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected all in update all accountLockRule")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AccountLockRule) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbmodels: no account_lock_rules provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(accountLockRuleColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	accountLockRuleUpsertCacheMut.RLock()
	cache, cached := accountLockRuleUpsertCache[key]
	accountLockRuleUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			accountLockRuleAllColumns,
			accountLockRuleColumnsWithDefault,
			accountLockRuleColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			accountLockRuleAllColumns,
			accountLockRulePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbmodels: unable to upsert account_lock_rules, could not build update column list")
		}

		ret := strmangle.SetComplement(accountLockRuleAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(accountLockRulePrimaryKeyColumns) == 0 {
				return errors.New("dbmodels: unable to upsert account_lock_rules, could not build conflict column list")
			}

			conflict = make([]string, len(accountLockRulePrimaryKeyColumns))
			copy(conflict, accountLockRulePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"account_lock_rules\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(accountLockRuleType, accountLockRuleMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(accountLockRuleType, accountLockRuleMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to upsert account_lock_rules")
	}

	if !cached {
		accountLockRuleUpsertCacheMut.Lock()
		accountLockRuleUpsertCache[key] = cache
		accountLockRuleUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single AccountLockRule record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AccountLockRule) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbmodels: no AccountLockRule provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), accountLockRulePrimaryKeyMapping)
	sql := "DELETE FROM \"account_lock_rules\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete from account_lock_rules")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by delete for account_lock_rules")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q accountLockRuleQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbmodels: no accountLockRuleQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from account_lock_rules")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for account_lock_rules")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AccountLockRuleSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(accountLockRuleBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountLockRulePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"account_lock_rules\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accountLockRulePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from accountLockRule slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for account_lock_rules")
	}

	if len(accountLockRuleAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AccountLockRule) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAccountLockRule(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AccountLockRuleSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AccountLockRuleSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountLockRulePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"account_lock_rules\".* FROM \"account_lock_rules\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accountLockRulePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to reload all in AccountLockRuleSlice")
	}

	*o = slice

	return nil
}

// AccountLockRuleExists checks if the AccountLockRule row exists.
func AccountLockRuleExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"account_lock_rules\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: unable to check if account_lock_rules exists")
	}

	return exists, nil
}

// Exists checks if the AccountLockRule row exists.
func (o *AccountLockRule) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AccountLockRuleExists(ctx, exec, o.ID)
}
