// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// AircraftFacility is an object representing the database table.
type AircraftFacility struct {
	ID         int64  `boil:"id" json:"id" toml:"id" yaml:"id"`
	AircraftID string `boil:"aircraft_id" json:"aircraft_id" toml:"aircraft_id" yaml:"aircraft_id"`
	FacilityID string `boil:"facility_id" json:"facility_id" toml:"facility_id" yaml:"facility_id"`

	R *aircraftFacilityR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L aircraftFacilityL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AircraftFacilityColumns = struct {
	ID         string
	AircraftID string
	FacilityID string
}{
	ID:         "id",
	AircraftID: "aircraft_id",
	FacilityID: "facility_id",
}

var AircraftFacilityTableColumns = struct {
	ID         string
	AircraftID string
	FacilityID string
}{
	ID:         "aircraft_facilities.id",
	AircraftID: "aircraft_facilities.aircraft_id",
	FacilityID: "aircraft_facilities.facility_id",
}

// Generated where

type whereHelperint64 struct{ field string }

func (w whereHelperint64) EQ(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint64) NEQ(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint64) LT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint64) LTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint64) GT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint64) GTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint64) IN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var AircraftFacilityWhere = struct {
	ID         whereHelperint64
	AircraftID whereHelperstring
	FacilityID whereHelperstring
}{
	ID:         whereHelperint64{field: "\"aircraft_facilities\".\"id\""},
	AircraftID: whereHelperstring{field: "\"aircraft_facilities\".\"aircraft_id\""},
	FacilityID: whereHelperstring{field: "\"aircraft_facilities\".\"facility_id\""},
}

// AircraftFacilityRels is where relationship names are stored.
var AircraftFacilityRels = struct {
	Aircraft string
	Facility string
}{
	Aircraft: "Aircraft",
	Facility: "Facility",
}

// aircraftFacilityR is where relationships are stored.
type aircraftFacilityR struct {
	Aircraft *Aircraft `boil:"Aircraft" json:"Aircraft" toml:"Aircraft" yaml:"Aircraft"`
	Facility *Facility `boil:"Facility" json:"Facility" toml:"Facility" yaml:"Facility"`
}

// NewStruct creates a new relationship struct
func (*aircraftFacilityR) NewStruct() *aircraftFacilityR {
	return &aircraftFacilityR{}
}

func (o *AircraftFacility) GetAircraft() *Aircraft {
	if o == nil {
		return nil
	}

	return o.R.GetAircraft()
}

func (r *aircraftFacilityR) GetAircraft() *Aircraft {
	if r == nil {
		return nil
	}

	return r.Aircraft
}

func (o *AircraftFacility) GetFacility() *Facility {
	if o == nil {
		return nil
	}

	return o.R.GetFacility()
}

func (r *aircraftFacilityR) GetFacility() *Facility {
	if r == nil {
		return nil
	}

	return r.Facility
}

// aircraftFacilityL is where Load methods for each relationship are stored.
type aircraftFacilityL struct{}

var (
	aircraftFacilityAllColumns            = []string{"id", "aircraft_id", "facility_id"}
	aircraftFacilityColumnsWithoutDefault = []string{"aircraft_id", "facility_id"}
	aircraftFacilityColumnsWithDefault    = []string{"id"}
	aircraftFacilityPrimaryKeyColumns     = []string{"id"}
	aircraftFacilityGeneratedColumns      = []string{}
)

type (
	// AircraftFacilitySlice is an alias for a slice of pointers to AircraftFacility.
	// This should almost always be used instead of []AircraftFacility.
	AircraftFacilitySlice []*AircraftFacility
	// AircraftFacilityHook is the signature for custom AircraftFacility hook methods
	AircraftFacilityHook func(context.Context, boil.ContextExecutor, *AircraftFacility) error

	aircraftFacilityQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	aircraftFacilityType                 = reflect.TypeOf(&AircraftFacility{})
	aircraftFacilityMapping              = queries.MakeStructMapping(aircraftFacilityType)
	aircraftFacilityPrimaryKeyMapping, _ = queries.BindMapping(aircraftFacilityType, aircraftFacilityMapping, aircraftFacilityPrimaryKeyColumns)
	aircraftFacilityInsertCacheMut       sync.RWMutex
	aircraftFacilityInsertCache          = make(map[string]insertCache)
	aircraftFacilityUpdateCacheMut       sync.RWMutex
	aircraftFacilityUpdateCache          = make(map[string]updateCache)
	aircraftFacilityUpsertCacheMut       sync.RWMutex
	aircraftFacilityUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var aircraftFacilityAfterSelectMu sync.Mutex
var aircraftFacilityAfterSelectHooks []AircraftFacilityHook

var aircraftFacilityBeforeInsertMu sync.Mutex
var aircraftFacilityBeforeInsertHooks []AircraftFacilityHook
var aircraftFacilityAfterInsertMu sync.Mutex
var aircraftFacilityAfterInsertHooks []AircraftFacilityHook

var aircraftFacilityBeforeUpdateMu sync.Mutex
var aircraftFacilityBeforeUpdateHooks []AircraftFacilityHook
var aircraftFacilityAfterUpdateMu sync.Mutex
var aircraftFacilityAfterUpdateHooks []AircraftFacilityHook

var aircraftFacilityBeforeDeleteMu sync.Mutex
var aircraftFacilityBeforeDeleteHooks []AircraftFacilityHook
var aircraftFacilityAfterDeleteMu sync.Mutex
var aircraftFacilityAfterDeleteHooks []AircraftFacilityHook

var aircraftFacilityBeforeUpsertMu sync.Mutex
var aircraftFacilityBeforeUpsertHooks []AircraftFacilityHook
var aircraftFacilityAfterUpsertMu sync.Mutex
var aircraftFacilityAfterUpsertHooks []AircraftFacilityHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AircraftFacility) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range aircraftFacilityAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AircraftFacility) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range aircraftFacilityBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AircraftFacility) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range aircraftFacilityAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AircraftFacility) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range aircraftFacilityBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AircraftFacility) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range aircraftFacilityAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AircraftFacility) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range aircraftFacilityBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AircraftFacility) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range aircraftFacilityAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AircraftFacility) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range aircraftFacilityBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AircraftFacility) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range aircraftFacilityAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAircraftFacilityHook registers your hook function for all future operations.
func AddAircraftFacilityHook(hookPoint boil.HookPoint, aircraftFacilityHook AircraftFacilityHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		aircraftFacilityAfterSelectMu.Lock()
		aircraftFacilityAfterSelectHooks = append(aircraftFacilityAfterSelectHooks, aircraftFacilityHook)
		aircraftFacilityAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		aircraftFacilityBeforeInsertMu.Lock()
		aircraftFacilityBeforeInsertHooks = append(aircraftFacilityBeforeInsertHooks, aircraftFacilityHook)
		aircraftFacilityBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		aircraftFacilityAfterInsertMu.Lock()
		aircraftFacilityAfterInsertHooks = append(aircraftFacilityAfterInsertHooks, aircraftFacilityHook)
		aircraftFacilityAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		aircraftFacilityBeforeUpdateMu.Lock()
		aircraftFacilityBeforeUpdateHooks = append(aircraftFacilityBeforeUpdateHooks, aircraftFacilityHook)
		aircraftFacilityBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		aircraftFacilityAfterUpdateMu.Lock()
		aircraftFacilityAfterUpdateHooks = append(aircraftFacilityAfterUpdateHooks, aircraftFacilityHook)
		aircraftFacilityAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		aircraftFacilityBeforeDeleteMu.Lock()
		aircraftFacilityBeforeDeleteHooks = append(aircraftFacilityBeforeDeleteHooks, aircraftFacilityHook)
		aircraftFacilityBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		aircraftFacilityAfterDeleteMu.Lock()
		aircraftFacilityAfterDeleteHooks = append(aircraftFacilityAfterDeleteHooks, aircraftFacilityHook)
		aircraftFacilityAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		aircraftFacilityBeforeUpsertMu.Lock()
		aircraftFacilityBeforeUpsertHooks = append(aircraftFacilityBeforeUpsertHooks, aircraftFacilityHook)
		aircraftFacilityBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		aircraftFacilityAfterUpsertMu.Lock()
		aircraftFacilityAfterUpsertHooks = append(aircraftFacilityAfterUpsertHooks, aircraftFacilityHook)
		aircraftFacilityAfterUpsertMu.Unlock()
	}
}

// One returns a single aircraftFacility record from the query.
func (q aircraftFacilityQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AircraftFacility, error) {
	o := &AircraftFacility{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: failed to execute a one query for aircraft_facilities")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all AircraftFacility records from the query.
func (q aircraftFacilityQuery) All(ctx context.Context, exec boil.ContextExecutor) (AircraftFacilitySlice, error) {
	var o []*AircraftFacility

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbmodels: failed to assign all query results to AircraftFacility slice")
	}

	if len(aircraftFacilityAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all AircraftFacility records in the query.
func (q aircraftFacilityQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to count aircraft_facilities rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q aircraftFacilityQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: failed to check if aircraft_facilities exists")
	}

	return count > 0, nil
}

// Aircraft pointed to by the foreign key.
func (o *AircraftFacility) Aircraft(mods ...qm.QueryMod) aircraftQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.AircraftID),
	}

	queryMods = append(queryMods, mods...)

	return Aircrafts(queryMods...)
}

// Facility pointed to by the foreign key.
func (o *AircraftFacility) Facility(mods ...qm.QueryMod) facilityQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.FacilityID),
	}

	queryMods = append(queryMods, mods...)

	return Facilities(queryMods...)
}

// LoadAircraft allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (aircraftFacilityL) LoadAircraft(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAircraftFacility interface{}, mods queries.Applicator) error {
	var slice []*AircraftFacility
	var object *AircraftFacility

	if singular {
		var ok bool
		object, ok = maybeAircraftFacility.(*AircraftFacility)
		if !ok {
			object = new(AircraftFacility)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAircraftFacility)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAircraftFacility))
			}
		}
	} else {
		s, ok := maybeAircraftFacility.(*[]*AircraftFacility)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAircraftFacility)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAircraftFacility))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &aircraftFacilityR{}
		}
		args[object.AircraftID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &aircraftFacilityR{}
			}

			args[obj.AircraftID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`aircraft`),
		qm.WhereIn(`aircraft.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Aircraft")
	}

	var resultSlice []*Aircraft
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Aircraft")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for aircraft")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for aircraft")
	}

	if len(aircraftAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Aircraft = foreign
		if foreign.R == nil {
			foreign.R = &aircraftR{}
		}
		foreign.R.AircraftFacilities = append(foreign.R.AircraftFacilities, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.AircraftID == foreign.ID {
				local.R.Aircraft = foreign
				if foreign.R == nil {
					foreign.R = &aircraftR{}
				}
				foreign.R.AircraftFacilities = append(foreign.R.AircraftFacilities, local)
				break
			}
		}
	}

	return nil
}

// LoadFacility allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (aircraftFacilityL) LoadFacility(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAircraftFacility interface{}, mods queries.Applicator) error {
	var slice []*AircraftFacility
	var object *AircraftFacility

	if singular {
		var ok bool
		object, ok = maybeAircraftFacility.(*AircraftFacility)
		if !ok {
			object = new(AircraftFacility)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAircraftFacility)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAircraftFacility))
			}
		}
	} else {
		s, ok := maybeAircraftFacility.(*[]*AircraftFacility)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAircraftFacility)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAircraftFacility))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &aircraftFacilityR{}
		}
		args[object.FacilityID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &aircraftFacilityR{}
			}

			args[obj.FacilityID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`facility`),
		qm.WhereIn(`facility.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Facility")
	}

	var resultSlice []*Facility
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Facility")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for facility")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for facility")
	}

	if len(facilityAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Facility = foreign
		if foreign.R == nil {
			foreign.R = &facilityR{}
		}
		foreign.R.AircraftFacilities = append(foreign.R.AircraftFacilities, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.FacilityID == foreign.ID {
				local.R.Facility = foreign
				if foreign.R == nil {
					foreign.R = &facilityR{}
				}
				foreign.R.AircraftFacilities = append(foreign.R.AircraftFacilities, local)
				break
			}
		}
	}

	return nil
}

// SetAircraft of the aircraftFacility to the related item.
// Sets o.R.Aircraft to related.
// Adds o to related.R.AircraftFacilities.
func (o *AircraftFacility) SetAircraft(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Aircraft) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"aircraft_facilities\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"aircraft_id"}),
		strmangle.WhereClause("\"", "\"", 2, aircraftFacilityPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.AircraftID = related.ID
	if o.R == nil {
		o.R = &aircraftFacilityR{
			Aircraft: related,
		}
	} else {
		o.R.Aircraft = related
	}

	if related.R == nil {
		related.R = &aircraftR{
			AircraftFacilities: AircraftFacilitySlice{o},
		}
	} else {
		related.R.AircraftFacilities = append(related.R.AircraftFacilities, o)
	}

	return nil
}

// SetFacility of the aircraftFacility to the related item.
// Sets o.R.Facility to related.
// Adds o to related.R.AircraftFacilities.
func (o *AircraftFacility) SetFacility(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Facility) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"aircraft_facilities\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"facility_id"}),
		strmangle.WhereClause("\"", "\"", 2, aircraftFacilityPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.FacilityID = related.ID
	if o.R == nil {
		o.R = &aircraftFacilityR{
			Facility: related,
		}
	} else {
		o.R.Facility = related
	}

	if related.R == nil {
		related.R = &facilityR{
			AircraftFacilities: AircraftFacilitySlice{o},
		}
	} else {
		related.R.AircraftFacilities = append(related.R.AircraftFacilities, o)
	}

	return nil
}

// AircraftFacilities retrieves all the records using an executor.
func AircraftFacilities(mods ...qm.QueryMod) aircraftFacilityQuery {
	mods = append(mods, qm.From("\"aircraft_facilities\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"aircraft_facilities\".*"})
	}

	return aircraftFacilityQuery{q}
}

// FindAircraftFacility retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAircraftFacility(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*AircraftFacility, error) {
	aircraftFacilityObj := &AircraftFacility{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"aircraft_facilities\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, aircraftFacilityObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: unable to select from aircraft_facilities")
	}

	if err = aircraftFacilityObj.doAfterSelectHooks(ctx, exec); err != nil {
		return aircraftFacilityObj, err
	}

	return aircraftFacilityObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AircraftFacility) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodels: no aircraft_facilities provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(aircraftFacilityColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	aircraftFacilityInsertCacheMut.RLock()
	cache, cached := aircraftFacilityInsertCache[key]
	aircraftFacilityInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			aircraftFacilityAllColumns,
			aircraftFacilityColumnsWithDefault,
			aircraftFacilityColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(aircraftFacilityType, aircraftFacilityMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(aircraftFacilityType, aircraftFacilityMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"aircraft_facilities\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"aircraft_facilities\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to insert into aircraft_facilities")
	}

	if !cached {
		aircraftFacilityInsertCacheMut.Lock()
		aircraftFacilityInsertCache[key] = cache
		aircraftFacilityInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the AircraftFacility.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AircraftFacility) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	aircraftFacilityUpdateCacheMut.RLock()
	cache, cached := aircraftFacilityUpdateCache[key]
	aircraftFacilityUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			aircraftFacilityAllColumns,
			aircraftFacilityPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbmodels: unable to update aircraft_facilities, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"aircraft_facilities\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, aircraftFacilityPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(aircraftFacilityType, aircraftFacilityMapping, append(wl, aircraftFacilityPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update aircraft_facilities row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by update for aircraft_facilities")
	}

	if !cached {
		aircraftFacilityUpdateCacheMut.Lock()
		aircraftFacilityUpdateCache[key] = cache
		aircraftFacilityUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q aircraftFacilityQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all for aircraft_facilities")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected for aircraft_facilities")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AircraftFacilitySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbmodels: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), aircraftFacilityPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"aircraft_facilities\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, aircraftFacilityPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all in aircraftFacility slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected all in update all aircraftFacility")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AircraftFacility) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbmodels: no aircraft_facilities provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(aircraftFacilityColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	aircraftFacilityUpsertCacheMut.RLock()
	cache, cached := aircraftFacilityUpsertCache[key]
	aircraftFacilityUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			aircraftFacilityAllColumns,
			aircraftFacilityColumnsWithDefault,
			aircraftFacilityColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			aircraftFacilityAllColumns,
			aircraftFacilityPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbmodels: unable to upsert aircraft_facilities, could not build update column list")
		}

		ret := strmangle.SetComplement(aircraftFacilityAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(aircraftFacilityPrimaryKeyColumns) == 0 {
				return errors.New("dbmodels: unable to upsert aircraft_facilities, could not build conflict column list")
			}

			conflict = make([]string, len(aircraftFacilityPrimaryKeyColumns))
			copy(conflict, aircraftFacilityPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"aircraft_facilities\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(aircraftFacilityType, aircraftFacilityMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(aircraftFacilityType, aircraftFacilityMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to upsert aircraft_facilities")
	}

	if !cached {
		aircraftFacilityUpsertCacheMut.Lock()
		aircraftFacilityUpsertCache[key] = cache
		aircraftFacilityUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single AircraftFacility record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AircraftFacility) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbmodels: no AircraftFacility provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), aircraftFacilityPrimaryKeyMapping)
	sql := "DELETE FROM \"aircraft_facilities\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete from aircraft_facilities")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by delete for aircraft_facilities")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q aircraftFacilityQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbmodels: no aircraftFacilityQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from aircraft_facilities")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for aircraft_facilities")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AircraftFacilitySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(aircraftFacilityBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), aircraftFacilityPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"aircraft_facilities\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, aircraftFacilityPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from aircraftFacility slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for aircraft_facilities")
	}

	if len(aircraftFacilityAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AircraftFacility) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAircraftFacility(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AircraftFacilitySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AircraftFacilitySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), aircraftFacilityPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"aircraft_facilities\".* FROM \"aircraft_facilities\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, aircraftFacilityPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to reload all in AircraftFacilitySlice")
	}

	*o = slice

	return nil
}

// AircraftFacilityExists checks if the AircraftFacility row exists.
func AircraftFacilityExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"aircraft_facilities\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: unable to check if aircraft_facilities exists")
	}

	return exists, nil
}

// Exists checks if the AircraftFacility row exists.
func (o *AircraftFacility) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AircraftFacilityExists(ctx, exec, o.ID)
}
