// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// FlightsGroup is an object representing the database table.
type FlightsGroup struct {
	ID            string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt     time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt     time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	AircraftID    null.String `boil:"aircraft_id" json:"aircraft_id,omitempty" toml:"aircraft_id" yaml:"aircraft_id,omitempty"`
	FromAirportID string      `boil:"from_airport_id" json:"from_airport_id" toml:"from_airport_id" yaml:"from_airport_id"`
	ToAirportID   string      `boil:"to_airport_id" json:"to_airport_id" toml:"to_airport_id" yaml:"to_airport_id"`
	Passenger     int         `boil:"passenger" json:"passenger" toml:"passenger" yaml:"passenger"`
	DepartsAt     time.Time   `boil:"departs_at" json:"departs_at" toml:"departs_at" yaml:"departs_at"`
	ArrivesAt     null.Time   `boil:"arrives_at" json:"arrives_at,omitempty" toml:"arrives_at" yaml:"arrives_at,omitempty"`
	TeamID        null.String `boil:"team_id" json:"team_id,omitempty" toml:"team_id" yaml:"team_id,omitempty"`
	UserID        null.Int    `boil:"user_id" json:"user_id,omitempty" toml:"user_id" yaml:"user_id,omitempty"`

	R *flightsGroupR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L flightsGroupL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var FlightsGroupColumns = struct {
	ID            string
	CreatedAt     string
	UpdatedAt     string
	AircraftID    string
	FromAirportID string
	ToAirportID   string
	Passenger     string
	DepartsAt     string
	ArrivesAt     string
	TeamID        string
	UserID        string
}{
	ID:            "id",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
	AircraftID:    "aircraft_id",
	FromAirportID: "from_airport_id",
	ToAirportID:   "to_airport_id",
	Passenger:     "passenger",
	DepartsAt:     "departs_at",
	ArrivesAt:     "arrives_at",
	TeamID:        "team_id",
	UserID:        "user_id",
}

var FlightsGroupTableColumns = struct {
	ID            string
	CreatedAt     string
	UpdatedAt     string
	AircraftID    string
	FromAirportID string
	ToAirportID   string
	Passenger     string
	DepartsAt     string
	ArrivesAt     string
	TeamID        string
	UserID        string
}{
	ID:            "flights_group.id",
	CreatedAt:     "flights_group.created_at",
	UpdatedAt:     "flights_group.updated_at",
	AircraftID:    "flights_group.aircraft_id",
	FromAirportID: "flights_group.from_airport_id",
	ToAirportID:   "flights_group.to_airport_id",
	Passenger:     "flights_group.passenger",
	DepartsAt:     "flights_group.departs_at",
	ArrivesAt:     "flights_group.arrives_at",
	TeamID:        "flights_group.team_id",
	UserID:        "flights_group.user_id",
}

// Generated where

var FlightsGroupWhere = struct {
	ID            whereHelperstring
	CreatedAt     whereHelpertime_Time
	UpdatedAt     whereHelpertime_Time
	AircraftID    whereHelpernull_String
	FromAirportID whereHelperstring
	ToAirportID   whereHelperstring
	Passenger     whereHelperint
	DepartsAt     whereHelpertime_Time
	ArrivesAt     whereHelpernull_Time
	TeamID        whereHelpernull_String
	UserID        whereHelpernull_Int
}{
	ID:            whereHelperstring{field: "\"flights_group\".\"id\""},
	CreatedAt:     whereHelpertime_Time{field: "\"flights_group\".\"created_at\""},
	UpdatedAt:     whereHelpertime_Time{field: "\"flights_group\".\"updated_at\""},
	AircraftID:    whereHelpernull_String{field: "\"flights_group\".\"aircraft_id\""},
	FromAirportID: whereHelperstring{field: "\"flights_group\".\"from_airport_id\""},
	ToAirportID:   whereHelperstring{field: "\"flights_group\".\"to_airport_id\""},
	Passenger:     whereHelperint{field: "\"flights_group\".\"passenger\""},
	DepartsAt:     whereHelpertime_Time{field: "\"flights_group\".\"departs_at\""},
	ArrivesAt:     whereHelpernull_Time{field: "\"flights_group\".\"arrives_at\""},
	TeamID:        whereHelpernull_String{field: "\"flights_group\".\"team_id\""},
	UserID:        whereHelpernull_Int{field: "\"flights_group\".\"user_id\""},
}

// FlightsGroupRels is where relationship names are stored.
var FlightsGroupRels = struct {
	Aircraft    string
	FromAirport string
	ToAirport   string
	User        string
	Team        string
}{
	Aircraft:    "Aircraft",
	FromAirport: "FromAirport",
	ToAirport:   "ToAirport",
	User:        "User",
	Team:        "Team",
}

// flightsGroupR is where relationships are stored.
type flightsGroupR struct {
	Aircraft    *Aircraft `boil:"Aircraft" json:"Aircraft" toml:"Aircraft" yaml:"Aircraft"`
	FromAirport *Airport  `boil:"FromAirport" json:"FromAirport" toml:"FromAirport" yaml:"FromAirport"`
	ToAirport   *Airport  `boil:"ToAirport" json:"ToAirport" toml:"ToAirport" yaml:"ToAirport"`
	User        *User     `boil:"User" json:"User" toml:"User" yaml:"User"`
	Team        *Team     `boil:"Team" json:"Team" toml:"Team" yaml:"Team"`
}

// NewStruct creates a new relationship struct
func (*flightsGroupR) NewStruct() *flightsGroupR {
	return &flightsGroupR{}
}

func (o *FlightsGroup) GetAircraft() *Aircraft {
	if o == nil {
		return nil
	}

	return o.R.GetAircraft()
}

func (r *flightsGroupR) GetAircraft() *Aircraft {
	if r == nil {
		return nil
	}

	return r.Aircraft
}

func (o *FlightsGroup) GetFromAirport() *Airport {
	if o == nil {
		return nil
	}

	return o.R.GetFromAirport()
}

func (r *flightsGroupR) GetFromAirport() *Airport {
	if r == nil {
		return nil
	}

	return r.FromAirport
}

func (o *FlightsGroup) GetToAirport() *Airport {
	if o == nil {
		return nil
	}

	return o.R.GetToAirport()
}

func (r *flightsGroupR) GetToAirport() *Airport {
	if r == nil {
		return nil
	}

	return r.ToAirport
}

func (o *FlightsGroup) GetUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUser()
}

func (r *flightsGroupR) GetUser() *User {
	if r == nil {
		return nil
	}

	return r.User
}

func (o *FlightsGroup) GetTeam() *Team {
	if o == nil {
		return nil
	}

	return o.R.GetTeam()
}

func (r *flightsGroupR) GetTeam() *Team {
	if r == nil {
		return nil
	}

	return r.Team
}

// flightsGroupL is where Load methods for each relationship are stored.
type flightsGroupL struct{}

var (
	flightsGroupAllColumns            = []string{"id", "created_at", "updated_at", "aircraft_id", "from_airport_id", "to_airport_id", "passenger", "departs_at", "arrives_at", "team_id", "user_id"}
	flightsGroupColumnsWithoutDefault = []string{"id", "updated_at", "from_airport_id", "to_airport_id", "departs_at"}
	flightsGroupColumnsWithDefault    = []string{"created_at", "aircraft_id", "passenger", "arrives_at", "team_id", "user_id"}
	flightsGroupPrimaryKeyColumns     = []string{"id"}
	flightsGroupGeneratedColumns      = []string{}
)

type (
	// FlightsGroupSlice is an alias for a slice of pointers to FlightsGroup.
	// This should almost always be used instead of []FlightsGroup.
	FlightsGroupSlice []*FlightsGroup
	// FlightsGroupHook is the signature for custom FlightsGroup hook methods
	FlightsGroupHook func(context.Context, boil.ContextExecutor, *FlightsGroup) error

	flightsGroupQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	flightsGroupType                 = reflect.TypeOf(&FlightsGroup{})
	flightsGroupMapping              = queries.MakeStructMapping(flightsGroupType)
	flightsGroupPrimaryKeyMapping, _ = queries.BindMapping(flightsGroupType, flightsGroupMapping, flightsGroupPrimaryKeyColumns)
	flightsGroupInsertCacheMut       sync.RWMutex
	flightsGroupInsertCache          = make(map[string]insertCache)
	flightsGroupUpdateCacheMut       sync.RWMutex
	flightsGroupUpdateCache          = make(map[string]updateCache)
	flightsGroupUpsertCacheMut       sync.RWMutex
	flightsGroupUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var flightsGroupAfterSelectMu sync.Mutex
var flightsGroupAfterSelectHooks []FlightsGroupHook

var flightsGroupBeforeInsertMu sync.Mutex
var flightsGroupBeforeInsertHooks []FlightsGroupHook
var flightsGroupAfterInsertMu sync.Mutex
var flightsGroupAfterInsertHooks []FlightsGroupHook

var flightsGroupBeforeUpdateMu sync.Mutex
var flightsGroupBeforeUpdateHooks []FlightsGroupHook
var flightsGroupAfterUpdateMu sync.Mutex
var flightsGroupAfterUpdateHooks []FlightsGroupHook

var flightsGroupBeforeDeleteMu sync.Mutex
var flightsGroupBeforeDeleteHooks []FlightsGroupHook
var flightsGroupAfterDeleteMu sync.Mutex
var flightsGroupAfterDeleteHooks []FlightsGroupHook

var flightsGroupBeforeUpsertMu sync.Mutex
var flightsGroupBeforeUpsertHooks []FlightsGroupHook
var flightsGroupAfterUpsertMu sync.Mutex
var flightsGroupAfterUpsertHooks []FlightsGroupHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *FlightsGroup) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightsGroupAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *FlightsGroup) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightsGroupBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *FlightsGroup) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightsGroupAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *FlightsGroup) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightsGroupBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *FlightsGroup) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightsGroupAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *FlightsGroup) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightsGroupBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *FlightsGroup) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightsGroupAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *FlightsGroup) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightsGroupBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *FlightsGroup) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightsGroupAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddFlightsGroupHook registers your hook function for all future operations.
func AddFlightsGroupHook(hookPoint boil.HookPoint, flightsGroupHook FlightsGroupHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		flightsGroupAfterSelectMu.Lock()
		flightsGroupAfterSelectHooks = append(flightsGroupAfterSelectHooks, flightsGroupHook)
		flightsGroupAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		flightsGroupBeforeInsertMu.Lock()
		flightsGroupBeforeInsertHooks = append(flightsGroupBeforeInsertHooks, flightsGroupHook)
		flightsGroupBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		flightsGroupAfterInsertMu.Lock()
		flightsGroupAfterInsertHooks = append(flightsGroupAfterInsertHooks, flightsGroupHook)
		flightsGroupAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		flightsGroupBeforeUpdateMu.Lock()
		flightsGroupBeforeUpdateHooks = append(flightsGroupBeforeUpdateHooks, flightsGroupHook)
		flightsGroupBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		flightsGroupAfterUpdateMu.Lock()
		flightsGroupAfterUpdateHooks = append(flightsGroupAfterUpdateHooks, flightsGroupHook)
		flightsGroupAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		flightsGroupBeforeDeleteMu.Lock()
		flightsGroupBeforeDeleteHooks = append(flightsGroupBeforeDeleteHooks, flightsGroupHook)
		flightsGroupBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		flightsGroupAfterDeleteMu.Lock()
		flightsGroupAfterDeleteHooks = append(flightsGroupAfterDeleteHooks, flightsGroupHook)
		flightsGroupAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		flightsGroupBeforeUpsertMu.Lock()
		flightsGroupBeforeUpsertHooks = append(flightsGroupBeforeUpsertHooks, flightsGroupHook)
		flightsGroupBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		flightsGroupAfterUpsertMu.Lock()
		flightsGroupAfterUpsertHooks = append(flightsGroupAfterUpsertHooks, flightsGroupHook)
		flightsGroupAfterUpsertMu.Unlock()
	}
}

// One returns a single flightsGroup record from the query.
func (q flightsGroupQuery) One(ctx context.Context, exec boil.ContextExecutor) (*FlightsGroup, error) {
	o := &FlightsGroup{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: failed to execute a one query for flights_group")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all FlightsGroup records from the query.
func (q flightsGroupQuery) All(ctx context.Context, exec boil.ContextExecutor) (FlightsGroupSlice, error) {
	var o []*FlightsGroup

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbmodels: failed to assign all query results to FlightsGroup slice")
	}

	if len(flightsGroupAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all FlightsGroup records in the query.
func (q flightsGroupQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to count flights_group rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q flightsGroupQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: failed to check if flights_group exists")
	}

	return count > 0, nil
}

// Aircraft pointed to by the foreign key.
func (o *FlightsGroup) Aircraft(mods ...qm.QueryMod) aircraftQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.AircraftID),
	}

	queryMods = append(queryMods, mods...)

	return Aircrafts(queryMods...)
}

// FromAirport pointed to by the foreign key.
func (o *FlightsGroup) FromAirport(mods ...qm.QueryMod) airportQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.FromAirportID),
	}

	queryMods = append(queryMods, mods...)

	return Airports(queryMods...)
}

// ToAirport pointed to by the foreign key.
func (o *FlightsGroup) ToAirport(mods ...qm.QueryMod) airportQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ToAirportID),
	}

	queryMods = append(queryMods, mods...)

	return Airports(queryMods...)
}

// User pointed to by the foreign key.
func (o *FlightsGroup) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// Team pointed to by the foreign key.
func (o *FlightsGroup) Team(mods ...qm.QueryMod) teamQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.TeamID),
	}

	queryMods = append(queryMods, mods...)

	return Teams(queryMods...)
}

// LoadAircraft allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (flightsGroupL) LoadAircraft(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFlightsGroup interface{}, mods queries.Applicator) error {
	var slice []*FlightsGroup
	var object *FlightsGroup

	if singular {
		var ok bool
		object, ok = maybeFlightsGroup.(*FlightsGroup)
		if !ok {
			object = new(FlightsGroup)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFlightsGroup)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFlightsGroup))
			}
		}
	} else {
		s, ok := maybeFlightsGroup.(*[]*FlightsGroup)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFlightsGroup)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFlightsGroup))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &flightsGroupR{}
		}
		if !queries.IsNil(object.AircraftID) {
			args[object.AircraftID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &flightsGroupR{}
			}

			if !queries.IsNil(obj.AircraftID) {
				args[obj.AircraftID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`aircraft`),
		qm.WhereIn(`aircraft.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Aircraft")
	}

	var resultSlice []*Aircraft
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Aircraft")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for aircraft")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for aircraft")
	}

	if len(aircraftAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Aircraft = foreign
		if foreign.R == nil {
			foreign.R = &aircraftR{}
		}
		foreign.R.FlightsGroups = append(foreign.R.FlightsGroups, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.AircraftID, foreign.ID) {
				local.R.Aircraft = foreign
				if foreign.R == nil {
					foreign.R = &aircraftR{}
				}
				foreign.R.FlightsGroups = append(foreign.R.FlightsGroups, local)
				break
			}
		}
	}

	return nil
}

// LoadFromAirport allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (flightsGroupL) LoadFromAirport(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFlightsGroup interface{}, mods queries.Applicator) error {
	var slice []*FlightsGroup
	var object *FlightsGroup

	if singular {
		var ok bool
		object, ok = maybeFlightsGroup.(*FlightsGroup)
		if !ok {
			object = new(FlightsGroup)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFlightsGroup)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFlightsGroup))
			}
		}
	} else {
		s, ok := maybeFlightsGroup.(*[]*FlightsGroup)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFlightsGroup)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFlightsGroup))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &flightsGroupR{}
		}
		args[object.FromAirportID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &flightsGroupR{}
			}

			args[obj.FromAirportID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`airport`),
		qm.WhereIn(`airport.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Airport")
	}

	var resultSlice []*Airport
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Airport")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for airport")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for airport")
	}

	if len(airportAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.FromAirport = foreign
		if foreign.R == nil {
			foreign.R = &airportR{}
		}
		foreign.R.FromAirportFlightsGroups = append(foreign.R.FromAirportFlightsGroups, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.FromAirportID == foreign.ID {
				local.R.FromAirport = foreign
				if foreign.R == nil {
					foreign.R = &airportR{}
				}
				foreign.R.FromAirportFlightsGroups = append(foreign.R.FromAirportFlightsGroups, local)
				break
			}
		}
	}

	return nil
}

// LoadToAirport allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (flightsGroupL) LoadToAirport(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFlightsGroup interface{}, mods queries.Applicator) error {
	var slice []*FlightsGroup
	var object *FlightsGroup

	if singular {
		var ok bool
		object, ok = maybeFlightsGroup.(*FlightsGroup)
		if !ok {
			object = new(FlightsGroup)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFlightsGroup)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFlightsGroup))
			}
		}
	} else {
		s, ok := maybeFlightsGroup.(*[]*FlightsGroup)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFlightsGroup)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFlightsGroup))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &flightsGroupR{}
		}
		args[object.ToAirportID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &flightsGroupR{}
			}

			args[obj.ToAirportID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`airport`),
		qm.WhereIn(`airport.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Airport")
	}

	var resultSlice []*Airport
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Airport")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for airport")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for airport")
	}

	if len(airportAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ToAirport = foreign
		if foreign.R == nil {
			foreign.R = &airportR{}
		}
		foreign.R.ToAirportFlightsGroups = append(foreign.R.ToAirportFlightsGroups, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ToAirportID == foreign.ID {
				local.R.ToAirport = foreign
				if foreign.R == nil {
					foreign.R = &airportR{}
				}
				foreign.R.ToAirportFlightsGroups = append(foreign.R.ToAirportFlightsGroups, local)
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (flightsGroupL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFlightsGroup interface{}, mods queries.Applicator) error {
	var slice []*FlightsGroup
	var object *FlightsGroup

	if singular {
		var ok bool
		object, ok = maybeFlightsGroup.(*FlightsGroup)
		if !ok {
			object = new(FlightsGroup)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFlightsGroup)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFlightsGroup))
			}
		}
	} else {
		s, ok := maybeFlightsGroup.(*[]*FlightsGroup)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFlightsGroup)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFlightsGroup))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &flightsGroupR{}
		}
		if !queries.IsNil(object.UserID) {
			args[object.UserID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &flightsGroupR{}
			}

			if !queries.IsNil(obj.UserID) {
				args[obj.UserID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.FlightsGroups = append(foreign.R.FlightsGroups, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.UserID, foreign.ID) {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.FlightsGroups = append(foreign.R.FlightsGroups, local)
				break
			}
		}
	}

	return nil
}

// LoadTeam allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (flightsGroupL) LoadTeam(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFlightsGroup interface{}, mods queries.Applicator) error {
	var slice []*FlightsGroup
	var object *FlightsGroup

	if singular {
		var ok bool
		object, ok = maybeFlightsGroup.(*FlightsGroup)
		if !ok {
			object = new(FlightsGroup)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFlightsGroup)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFlightsGroup))
			}
		}
	} else {
		s, ok := maybeFlightsGroup.(*[]*FlightsGroup)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFlightsGroup)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFlightsGroup))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &flightsGroupR{}
		}
		if !queries.IsNil(object.TeamID) {
			args[object.TeamID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &flightsGroupR{}
			}

			if !queries.IsNil(obj.TeamID) {
				args[obj.TeamID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`team`),
		qm.WhereIn(`team.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Team")
	}

	var resultSlice []*Team
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Team")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for team")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for team")
	}

	if len(teamAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Team = foreign
		if foreign.R == nil {
			foreign.R = &teamR{}
		}
		foreign.R.FlightsGroups = append(foreign.R.FlightsGroups, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.TeamID, foreign.ID) {
				local.R.Team = foreign
				if foreign.R == nil {
					foreign.R = &teamR{}
				}
				foreign.R.FlightsGroups = append(foreign.R.FlightsGroups, local)
				break
			}
		}
	}

	return nil
}

// SetAircraft of the flightsGroup to the related item.
// Sets o.R.Aircraft to related.
// Adds o to related.R.FlightsGroups.
func (o *FlightsGroup) SetAircraft(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Aircraft) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"flights_group\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"aircraft_id"}),
		strmangle.WhereClause("\"", "\"", 2, flightsGroupPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.AircraftID, related.ID)
	if o.R == nil {
		o.R = &flightsGroupR{
			Aircraft: related,
		}
	} else {
		o.R.Aircraft = related
	}

	if related.R == nil {
		related.R = &aircraftR{
			FlightsGroups: FlightsGroupSlice{o},
		}
	} else {
		related.R.FlightsGroups = append(related.R.FlightsGroups, o)
	}

	return nil
}

// RemoveAircraft relationship.
// Sets o.R.Aircraft to nil.
// Removes o from all passed in related items' relationships struct.
func (o *FlightsGroup) RemoveAircraft(ctx context.Context, exec boil.ContextExecutor, related *Aircraft) error {
	var err error

	queries.SetScanner(&o.AircraftID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("aircraft_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Aircraft = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.FlightsGroups {
		if queries.Equal(o.AircraftID, ri.AircraftID) {
			continue
		}

		ln := len(related.R.FlightsGroups)
		if ln > 1 && i < ln-1 {
			related.R.FlightsGroups[i] = related.R.FlightsGroups[ln-1]
		}
		related.R.FlightsGroups = related.R.FlightsGroups[:ln-1]
		break
	}
	return nil
}

// SetFromAirport of the flightsGroup to the related item.
// Sets o.R.FromAirport to related.
// Adds o to related.R.FromAirportFlightsGroups.
func (o *FlightsGroup) SetFromAirport(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Airport) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"flights_group\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"from_airport_id"}),
		strmangle.WhereClause("\"", "\"", 2, flightsGroupPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.FromAirportID = related.ID
	if o.R == nil {
		o.R = &flightsGroupR{
			FromAirport: related,
		}
	} else {
		o.R.FromAirport = related
	}

	if related.R == nil {
		related.R = &airportR{
			FromAirportFlightsGroups: FlightsGroupSlice{o},
		}
	} else {
		related.R.FromAirportFlightsGroups = append(related.R.FromAirportFlightsGroups, o)
	}

	return nil
}

// SetToAirport of the flightsGroup to the related item.
// Sets o.R.ToAirport to related.
// Adds o to related.R.ToAirportFlightsGroups.
func (o *FlightsGroup) SetToAirport(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Airport) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"flights_group\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"to_airport_id"}),
		strmangle.WhereClause("\"", "\"", 2, flightsGroupPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ToAirportID = related.ID
	if o.R == nil {
		o.R = &flightsGroupR{
			ToAirport: related,
		}
	} else {
		o.R.ToAirport = related
	}

	if related.R == nil {
		related.R = &airportR{
			ToAirportFlightsGroups: FlightsGroupSlice{o},
		}
	} else {
		related.R.ToAirportFlightsGroups = append(related.R.ToAirportFlightsGroups, o)
	}

	return nil
}

// SetUser of the flightsGroup to the related item.
// Sets o.R.User to related.
// Adds o to related.R.FlightsGroups.
func (o *FlightsGroup) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"flights_group\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, flightsGroupPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.UserID, related.ID)
	if o.R == nil {
		o.R = &flightsGroupR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			FlightsGroups: FlightsGroupSlice{o},
		}
	} else {
		related.R.FlightsGroups = append(related.R.FlightsGroups, o)
	}

	return nil
}

// RemoveUser relationship.
// Sets o.R.User to nil.
// Removes o from all passed in related items' relationships struct.
func (o *FlightsGroup) RemoveUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.UserID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("user_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.User = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.FlightsGroups {
		if queries.Equal(o.UserID, ri.UserID) {
			continue
		}

		ln := len(related.R.FlightsGroups)
		if ln > 1 && i < ln-1 {
			related.R.FlightsGroups[i] = related.R.FlightsGroups[ln-1]
		}
		related.R.FlightsGroups = related.R.FlightsGroups[:ln-1]
		break
	}
	return nil
}

// SetTeam of the flightsGroup to the related item.
// Sets o.R.Team to related.
// Adds o to related.R.FlightsGroups.
func (o *FlightsGroup) SetTeam(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Team) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"flights_group\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"team_id"}),
		strmangle.WhereClause("\"", "\"", 2, flightsGroupPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.TeamID, related.ID)
	if o.R == nil {
		o.R = &flightsGroupR{
			Team: related,
		}
	} else {
		o.R.Team = related
	}

	if related.R == nil {
		related.R = &teamR{
			FlightsGroups: FlightsGroupSlice{o},
		}
	} else {
		related.R.FlightsGroups = append(related.R.FlightsGroups, o)
	}

	return nil
}

// RemoveTeam relationship.
// Sets o.R.Team to nil.
// Removes o from all passed in related items' relationships struct.
func (o *FlightsGroup) RemoveTeam(ctx context.Context, exec boil.ContextExecutor, related *Team) error {
	var err error

	queries.SetScanner(&o.TeamID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("team_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Team = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.FlightsGroups {
		if queries.Equal(o.TeamID, ri.TeamID) {
			continue
		}

		ln := len(related.R.FlightsGroups)
		if ln > 1 && i < ln-1 {
			related.R.FlightsGroups[i] = related.R.FlightsGroups[ln-1]
		}
		related.R.FlightsGroups = related.R.FlightsGroups[:ln-1]
		break
	}
	return nil
}

// FlightsGroups retrieves all the records using an executor.
func FlightsGroups(mods ...qm.QueryMod) flightsGroupQuery {
	mods = append(mods, qm.From("\"flights_group\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"flights_group\".*"})
	}

	return flightsGroupQuery{q}
}

// FindFlightsGroup retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindFlightsGroup(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*FlightsGroup, error) {
	flightsGroupObj := &FlightsGroup{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"flights_group\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, flightsGroupObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: unable to select from flights_group")
	}

	if err = flightsGroupObj.doAfterSelectHooks(ctx, exec); err != nil {
		return flightsGroupObj, err
	}

	return flightsGroupObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *FlightsGroup) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodels: no flights_group provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(flightsGroupColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	flightsGroupInsertCacheMut.RLock()
	cache, cached := flightsGroupInsertCache[key]
	flightsGroupInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			flightsGroupAllColumns,
			flightsGroupColumnsWithDefault,
			flightsGroupColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(flightsGroupType, flightsGroupMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(flightsGroupType, flightsGroupMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"flights_group\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"flights_group\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to insert into flights_group")
	}

	if !cached {
		flightsGroupInsertCacheMut.Lock()
		flightsGroupInsertCache[key] = cache
		flightsGroupInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the FlightsGroup.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *FlightsGroup) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	flightsGroupUpdateCacheMut.RLock()
	cache, cached := flightsGroupUpdateCache[key]
	flightsGroupUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			flightsGroupAllColumns,
			flightsGroupPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbmodels: unable to update flights_group, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"flights_group\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, flightsGroupPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(flightsGroupType, flightsGroupMapping, append(wl, flightsGroupPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update flights_group row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by update for flights_group")
	}

	if !cached {
		flightsGroupUpdateCacheMut.Lock()
		flightsGroupUpdateCache[key] = cache
		flightsGroupUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q flightsGroupQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all for flights_group")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected for flights_group")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o FlightsGroupSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbmodels: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), flightsGroupPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"flights_group\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, flightsGroupPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all in flightsGroup slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected all in update all flightsGroup")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *FlightsGroup) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbmodels: no flights_group provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(flightsGroupColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	flightsGroupUpsertCacheMut.RLock()
	cache, cached := flightsGroupUpsertCache[key]
	flightsGroupUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			flightsGroupAllColumns,
			flightsGroupColumnsWithDefault,
			flightsGroupColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			flightsGroupAllColumns,
			flightsGroupPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbmodels: unable to upsert flights_group, could not build update column list")
		}

		ret := strmangle.SetComplement(flightsGroupAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(flightsGroupPrimaryKeyColumns) == 0 {
				return errors.New("dbmodels: unable to upsert flights_group, could not build conflict column list")
			}

			conflict = make([]string, len(flightsGroupPrimaryKeyColumns))
			copy(conflict, flightsGroupPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"flights_group\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(flightsGroupType, flightsGroupMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(flightsGroupType, flightsGroupMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to upsert flights_group")
	}

	if !cached {
		flightsGroupUpsertCacheMut.Lock()
		flightsGroupUpsertCache[key] = cache
		flightsGroupUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single FlightsGroup record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *FlightsGroup) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbmodels: no FlightsGroup provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), flightsGroupPrimaryKeyMapping)
	sql := "DELETE FROM \"flights_group\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete from flights_group")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by delete for flights_group")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q flightsGroupQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbmodels: no flightsGroupQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from flights_group")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for flights_group")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o FlightsGroupSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(flightsGroupBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), flightsGroupPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"flights_group\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, flightsGroupPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from flightsGroup slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for flights_group")
	}

	if len(flightsGroupAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *FlightsGroup) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindFlightsGroup(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *FlightsGroupSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := FlightsGroupSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), flightsGroupPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"flights_group\".* FROM \"flights_group\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, flightsGroupPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to reload all in FlightsGroupSlice")
	}

	*o = slice

	return nil
}

// FlightsGroupExists checks if the FlightsGroup row exists.
func FlightsGroupExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"flights_group\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: unable to check if flights_group exists")
	}

	return exists, nil
}

// Exists checks if the FlightsGroup row exists.
func (o *FlightsGroup) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return FlightsGroupExists(ctx, exec, o.ID)
}
