// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// FlightsOld is an object representing the database table.
type FlightsOld struct {
	ID        int               `boil:"id" json:"id" toml:"id" yaml:"id"`
	Type      string            `boil:"type" json:"type" toml:"type" yaml:"type"`
	Flights   types.StringArray `boil:"flights" json:"flights" toml:"flights" yaml:"flights"`
	FullName  string            `boil:"full_name" json:"full_name" toml:"full_name" yaml:"full_name"`
	Email     string            `boil:"email" json:"email" toml:"email" yaml:"email"`
	CreatedAt time.Time         `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	CreatedBy int               `boil:"created_by" json:"created_by" toml:"created_by" yaml:"created_by"`
	UpdatedAt null.Time         `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	UpdatedBy null.Int          `boil:"updated_by" json:"updated_by,omitempty" toml:"updated_by" yaml:"updated_by,omitempty"`
	Phone     null.String       `boil:"phone" json:"phone,omitempty" toml:"phone" yaml:"phone,omitempty"`

	R *flightsOldR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L flightsOldL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var FlightsOldColumns = struct {
	ID        string
	Type      string
	Flights   string
	FullName  string
	Email     string
	CreatedAt string
	CreatedBy string
	UpdatedAt string
	UpdatedBy string
	Phone     string
}{
	ID:        "id",
	Type:      "type",
	Flights:   "flights",
	FullName:  "full_name",
	Email:     "email",
	CreatedAt: "created_at",
	CreatedBy: "created_by",
	UpdatedAt: "updated_at",
	UpdatedBy: "updated_by",
	Phone:     "phone",
}

var FlightsOldTableColumns = struct {
	ID        string
	Type      string
	Flights   string
	FullName  string
	Email     string
	CreatedAt string
	CreatedBy string
	UpdatedAt string
	UpdatedBy string
	Phone     string
}{
	ID:        "flights_old.id",
	Type:      "flights_old.type",
	Flights:   "flights_old.flights",
	FullName:  "flights_old.full_name",
	Email:     "flights_old.email",
	CreatedAt: "flights_old.created_at",
	CreatedBy: "flights_old.created_by",
	UpdatedAt: "flights_old.updated_at",
	UpdatedBy: "flights_old.updated_by",
	Phone:     "flights_old.phone",
}

// Generated where

var FlightsOldWhere = struct {
	ID        whereHelperint
	Type      whereHelperstring
	Flights   whereHelpertypes_StringArray
	FullName  whereHelperstring
	Email     whereHelperstring
	CreatedAt whereHelpertime_Time
	CreatedBy whereHelperint
	UpdatedAt whereHelpernull_Time
	UpdatedBy whereHelpernull_Int
	Phone     whereHelpernull_String
}{
	ID:        whereHelperint{field: "\"flights_old\".\"id\""},
	Type:      whereHelperstring{field: "\"flights_old\".\"type\""},
	Flights:   whereHelpertypes_StringArray{field: "\"flights_old\".\"flights\""},
	FullName:  whereHelperstring{field: "\"flights_old\".\"full_name\""},
	Email:     whereHelperstring{field: "\"flights_old\".\"email\""},
	CreatedAt: whereHelpertime_Time{field: "\"flights_old\".\"created_at\""},
	CreatedBy: whereHelperint{field: "\"flights_old\".\"created_by\""},
	UpdatedAt: whereHelpernull_Time{field: "\"flights_old\".\"updated_at\""},
	UpdatedBy: whereHelpernull_Int{field: "\"flights_old\".\"updated_by\""},
	Phone:     whereHelpernull_String{field: "\"flights_old\".\"phone\""},
}

// FlightsOldRels is where relationship names are stored.
var FlightsOldRels = struct {
}{}

// flightsOldR is where relationships are stored.
type flightsOldR struct {
}

// NewStruct creates a new relationship struct
func (*flightsOldR) NewStruct() *flightsOldR {
	return &flightsOldR{}
}

// flightsOldL is where Load methods for each relationship are stored.
type flightsOldL struct{}

var (
	flightsOldAllColumns            = []string{"id", "type", "flights", "full_name", "email", "created_at", "created_by", "updated_at", "updated_by", "phone"}
	flightsOldColumnsWithoutDefault = []string{"type", "flights", "full_name", "email", "created_at", "created_by"}
	flightsOldColumnsWithDefault    = []string{"id", "updated_at", "updated_by", "phone"}
	flightsOldPrimaryKeyColumns     = []string{"id"}
	flightsOldGeneratedColumns      = []string{}
)

type (
	// FlightsOldSlice is an alias for a slice of pointers to FlightsOld.
	// This should almost always be used instead of []FlightsOld.
	FlightsOldSlice []*FlightsOld
	// FlightsOldHook is the signature for custom FlightsOld hook methods
	FlightsOldHook func(context.Context, boil.ContextExecutor, *FlightsOld) error

	flightsOldQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	flightsOldType                 = reflect.TypeOf(&FlightsOld{})
	flightsOldMapping              = queries.MakeStructMapping(flightsOldType)
	flightsOldPrimaryKeyMapping, _ = queries.BindMapping(flightsOldType, flightsOldMapping, flightsOldPrimaryKeyColumns)
	flightsOldInsertCacheMut       sync.RWMutex
	flightsOldInsertCache          = make(map[string]insertCache)
	flightsOldUpdateCacheMut       sync.RWMutex
	flightsOldUpdateCache          = make(map[string]updateCache)
	flightsOldUpsertCacheMut       sync.RWMutex
	flightsOldUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var flightsOldAfterSelectMu sync.Mutex
var flightsOldAfterSelectHooks []FlightsOldHook

var flightsOldBeforeInsertMu sync.Mutex
var flightsOldBeforeInsertHooks []FlightsOldHook
var flightsOldAfterInsertMu sync.Mutex
var flightsOldAfterInsertHooks []FlightsOldHook

var flightsOldBeforeUpdateMu sync.Mutex
var flightsOldBeforeUpdateHooks []FlightsOldHook
var flightsOldAfterUpdateMu sync.Mutex
var flightsOldAfterUpdateHooks []FlightsOldHook

var flightsOldBeforeDeleteMu sync.Mutex
var flightsOldBeforeDeleteHooks []FlightsOldHook
var flightsOldAfterDeleteMu sync.Mutex
var flightsOldAfterDeleteHooks []FlightsOldHook

var flightsOldBeforeUpsertMu sync.Mutex
var flightsOldBeforeUpsertHooks []FlightsOldHook
var flightsOldAfterUpsertMu sync.Mutex
var flightsOldAfterUpsertHooks []FlightsOldHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *FlightsOld) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightsOldAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *FlightsOld) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightsOldBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *FlightsOld) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightsOldAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *FlightsOld) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightsOldBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *FlightsOld) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightsOldAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *FlightsOld) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightsOldBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *FlightsOld) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightsOldAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *FlightsOld) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightsOldBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *FlightsOld) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightsOldAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddFlightsOldHook registers your hook function for all future operations.
func AddFlightsOldHook(hookPoint boil.HookPoint, flightsOldHook FlightsOldHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		flightsOldAfterSelectMu.Lock()
		flightsOldAfterSelectHooks = append(flightsOldAfterSelectHooks, flightsOldHook)
		flightsOldAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		flightsOldBeforeInsertMu.Lock()
		flightsOldBeforeInsertHooks = append(flightsOldBeforeInsertHooks, flightsOldHook)
		flightsOldBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		flightsOldAfterInsertMu.Lock()
		flightsOldAfterInsertHooks = append(flightsOldAfterInsertHooks, flightsOldHook)
		flightsOldAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		flightsOldBeforeUpdateMu.Lock()
		flightsOldBeforeUpdateHooks = append(flightsOldBeforeUpdateHooks, flightsOldHook)
		flightsOldBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		flightsOldAfterUpdateMu.Lock()
		flightsOldAfterUpdateHooks = append(flightsOldAfterUpdateHooks, flightsOldHook)
		flightsOldAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		flightsOldBeforeDeleteMu.Lock()
		flightsOldBeforeDeleteHooks = append(flightsOldBeforeDeleteHooks, flightsOldHook)
		flightsOldBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		flightsOldAfterDeleteMu.Lock()
		flightsOldAfterDeleteHooks = append(flightsOldAfterDeleteHooks, flightsOldHook)
		flightsOldAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		flightsOldBeforeUpsertMu.Lock()
		flightsOldBeforeUpsertHooks = append(flightsOldBeforeUpsertHooks, flightsOldHook)
		flightsOldBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		flightsOldAfterUpsertMu.Lock()
		flightsOldAfterUpsertHooks = append(flightsOldAfterUpsertHooks, flightsOldHook)
		flightsOldAfterUpsertMu.Unlock()
	}
}

// One returns a single flightsOld record from the query.
func (q flightsOldQuery) One(ctx context.Context, exec boil.ContextExecutor) (*FlightsOld, error) {
	o := &FlightsOld{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: failed to execute a one query for flights_old")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all FlightsOld records from the query.
func (q flightsOldQuery) All(ctx context.Context, exec boil.ContextExecutor) (FlightsOldSlice, error) {
	var o []*FlightsOld

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbmodels: failed to assign all query results to FlightsOld slice")
	}

	if len(flightsOldAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all FlightsOld records in the query.
func (q flightsOldQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to count flights_old rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q flightsOldQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: failed to check if flights_old exists")
	}

	return count > 0, nil
}

// FlightsOlds retrieves all the records using an executor.
func FlightsOlds(mods ...qm.QueryMod) flightsOldQuery {
	mods = append(mods, qm.From("\"flights_old\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"flights_old\".*"})
	}

	return flightsOldQuery{q}
}

// FindFlightsOld retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindFlightsOld(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*FlightsOld, error) {
	flightsOldObj := &FlightsOld{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"flights_old\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, flightsOldObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: unable to select from flights_old")
	}

	if err = flightsOldObj.doAfterSelectHooks(ctx, exec); err != nil {
		return flightsOldObj, err
	}

	return flightsOldObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *FlightsOld) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodels: no flights_old provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(flightsOldColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	flightsOldInsertCacheMut.RLock()
	cache, cached := flightsOldInsertCache[key]
	flightsOldInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			flightsOldAllColumns,
			flightsOldColumnsWithDefault,
			flightsOldColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(flightsOldType, flightsOldMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(flightsOldType, flightsOldMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"flights_old\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"flights_old\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to insert into flights_old")
	}

	if !cached {
		flightsOldInsertCacheMut.Lock()
		flightsOldInsertCache[key] = cache
		flightsOldInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the FlightsOld.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *FlightsOld) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	flightsOldUpdateCacheMut.RLock()
	cache, cached := flightsOldUpdateCache[key]
	flightsOldUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			flightsOldAllColumns,
			flightsOldPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbmodels: unable to update flights_old, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"flights_old\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, flightsOldPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(flightsOldType, flightsOldMapping, append(wl, flightsOldPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update flights_old row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by update for flights_old")
	}

	if !cached {
		flightsOldUpdateCacheMut.Lock()
		flightsOldUpdateCache[key] = cache
		flightsOldUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q flightsOldQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all for flights_old")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected for flights_old")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o FlightsOldSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbmodels: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), flightsOldPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"flights_old\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, flightsOldPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all in flightsOld slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected all in update all flightsOld")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *FlightsOld) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbmodels: no flights_old provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(flightsOldColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	flightsOldUpsertCacheMut.RLock()
	cache, cached := flightsOldUpsertCache[key]
	flightsOldUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			flightsOldAllColumns,
			flightsOldColumnsWithDefault,
			flightsOldColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			flightsOldAllColumns,
			flightsOldPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbmodels: unable to upsert flights_old, could not build update column list")
		}

		ret := strmangle.SetComplement(flightsOldAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(flightsOldPrimaryKeyColumns) == 0 {
				return errors.New("dbmodels: unable to upsert flights_old, could not build conflict column list")
			}

			conflict = make([]string, len(flightsOldPrimaryKeyColumns))
			copy(conflict, flightsOldPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"flights_old\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(flightsOldType, flightsOldMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(flightsOldType, flightsOldMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to upsert flights_old")
	}

	if !cached {
		flightsOldUpsertCacheMut.Lock()
		flightsOldUpsertCache[key] = cache
		flightsOldUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single FlightsOld record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *FlightsOld) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbmodels: no FlightsOld provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), flightsOldPrimaryKeyMapping)
	sql := "DELETE FROM \"flights_old\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete from flights_old")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by delete for flights_old")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q flightsOldQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbmodels: no flightsOldQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from flights_old")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for flights_old")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o FlightsOldSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(flightsOldBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), flightsOldPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"flights_old\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, flightsOldPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from flightsOld slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for flights_old")
	}

	if len(flightsOldAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *FlightsOld) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindFlightsOld(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *FlightsOldSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := FlightsOldSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), flightsOldPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"flights_old\".* FROM \"flights_old\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, flightsOldPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to reload all in FlightsOldSlice")
	}

	*o = slice

	return nil
}

// FlightsOldExists checks if the FlightsOld row exists.
func FlightsOldExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"flights_old\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: unable to check if flights_old exists")
	}

	return exists, nil
}

// Exists checks if the FlightsOld row exists.
func (o *FlightsOld) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return FlightsOldExists(ctx, exec, o.ID)
}
