// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Flight is an object representing the database table.
type Flight struct {
	ID        int               `boil:"id" json:"id" toml:"id" yaml:"id"`
	Type      string            `boil:"type" json:"type" toml:"type" yaml:"type"`
	Flights   types.StringArray `boil:"flights" json:"flights" toml:"flights" yaml:"flights"`
	Fullname  string            `boil:"fullname" json:"fullname" toml:"fullname" yaml:"fullname"`
	Email     string            `boil:"email" json:"email" toml:"email" yaml:"email"`
	CreatedAt time.Time         `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	CreatedBy int               `boil:"created_by" json:"created_by" toml:"created_by" yaml:"created_by"`
	UpdatedAt null.Time         `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	UpdatedBy null.Int          `boil:"updated_by" json:"updated_by,omitempty" toml:"updated_by" yaml:"updated_by,omitempty"`

	R *flightR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L flightL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var FlightColumns = struct {
	ID        string
	Type      string
	Flights   string
	Fullname  string
	Email     string
	CreatedAt string
	CreatedBy string
	UpdatedAt string
	UpdatedBy string
}{
	ID:        "id",
	Type:      "type",
	Flights:   "flights",
	Fullname:  "fullname",
	Email:     "email",
	CreatedAt: "created_at",
	CreatedBy: "created_by",
	UpdatedAt: "updated_at",
	UpdatedBy: "updated_by",
}

var FlightTableColumns = struct {
	ID        string
	Type      string
	Flights   string
	Fullname  string
	Email     string
	CreatedAt string
	CreatedBy string
	UpdatedAt string
	UpdatedBy string
}{
	ID:        "flights.id",
	Type:      "flights.type",
	Flights:   "flights.flights",
	Fullname:  "flights.fullname",
	Email:     "flights.email",
	CreatedAt: "flights.created_at",
	CreatedBy: "flights.created_by",
	UpdatedAt: "flights.updated_at",
	UpdatedBy: "flights.updated_by",
}

// Generated where

var FlightWhere = struct {
	ID        whereHelperint
	Type      whereHelperstring
	Flights   whereHelpertypes_StringArray
	Fullname  whereHelperstring
	Email     whereHelperstring
	CreatedAt whereHelpertime_Time
	CreatedBy whereHelperint
	UpdatedAt whereHelpernull_Time
	UpdatedBy whereHelpernull_Int
}{
	ID:        whereHelperint{field: "\"flights\".\"id\""},
	Type:      whereHelperstring{field: "\"flights\".\"type\""},
	Flights:   whereHelpertypes_StringArray{field: "\"flights\".\"flights\""},
	Fullname:  whereHelperstring{field: "\"flights\".\"fullname\""},
	Email:     whereHelperstring{field: "\"flights\".\"email\""},
	CreatedAt: whereHelpertime_Time{field: "\"flights\".\"created_at\""},
	CreatedBy: whereHelperint{field: "\"flights\".\"created_by\""},
	UpdatedAt: whereHelpernull_Time{field: "\"flights\".\"updated_at\""},
	UpdatedBy: whereHelpernull_Int{field: "\"flights\".\"updated_by\""},
}

// FlightRels is where relationship names are stored.
var FlightRels = struct {
}{}

// flightR is where relationships are stored.
type flightR struct {
}

// NewStruct creates a new relationship struct
func (*flightR) NewStruct() *flightR {
	return &flightR{}
}

// flightL is where Load methods for each relationship are stored.
type flightL struct{}

var (
	flightAllColumns            = []string{"id", "type", "flights", "fullname", "email", "created_at", "created_by", "updated_at", "updated_by"}
	flightColumnsWithoutDefault = []string{"type", "flights", "fullname", "email", "created_at", "created_by"}
	flightColumnsWithDefault    = []string{"id", "updated_at", "updated_by"}
	flightPrimaryKeyColumns     = []string{"id"}
	flightGeneratedColumns      = []string{}
)

type (
	// FlightSlice is an alias for a slice of pointers to Flight.
	// This should almost always be used instead of []Flight.
	FlightSlice []*Flight
	// FlightHook is the signature for custom Flight hook methods
	FlightHook func(context.Context, boil.ContextExecutor, *Flight) error

	flightQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	flightType                 = reflect.TypeOf(&Flight{})
	flightMapping              = queries.MakeStructMapping(flightType)
	flightPrimaryKeyMapping, _ = queries.BindMapping(flightType, flightMapping, flightPrimaryKeyColumns)
	flightInsertCacheMut       sync.RWMutex
	flightInsertCache          = make(map[string]insertCache)
	flightUpdateCacheMut       sync.RWMutex
	flightUpdateCache          = make(map[string]updateCache)
	flightUpsertCacheMut       sync.RWMutex
	flightUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var flightAfterSelectMu sync.Mutex
var flightAfterSelectHooks []FlightHook

var flightBeforeInsertMu sync.Mutex
var flightBeforeInsertHooks []FlightHook
var flightAfterInsertMu sync.Mutex
var flightAfterInsertHooks []FlightHook

var flightBeforeUpdateMu sync.Mutex
var flightBeforeUpdateHooks []FlightHook
var flightAfterUpdateMu sync.Mutex
var flightAfterUpdateHooks []FlightHook

var flightBeforeDeleteMu sync.Mutex
var flightBeforeDeleteHooks []FlightHook
var flightAfterDeleteMu sync.Mutex
var flightAfterDeleteHooks []FlightHook

var flightBeforeUpsertMu sync.Mutex
var flightBeforeUpsertHooks []FlightHook
var flightAfterUpsertMu sync.Mutex
var flightAfterUpsertHooks []FlightHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Flight) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Flight) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Flight) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Flight) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Flight) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Flight) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Flight) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Flight) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Flight) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flightAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddFlightHook registers your hook function for all future operations.
func AddFlightHook(hookPoint boil.HookPoint, flightHook FlightHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		flightAfterSelectMu.Lock()
		flightAfterSelectHooks = append(flightAfterSelectHooks, flightHook)
		flightAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		flightBeforeInsertMu.Lock()
		flightBeforeInsertHooks = append(flightBeforeInsertHooks, flightHook)
		flightBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		flightAfterInsertMu.Lock()
		flightAfterInsertHooks = append(flightAfterInsertHooks, flightHook)
		flightAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		flightBeforeUpdateMu.Lock()
		flightBeforeUpdateHooks = append(flightBeforeUpdateHooks, flightHook)
		flightBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		flightAfterUpdateMu.Lock()
		flightAfterUpdateHooks = append(flightAfterUpdateHooks, flightHook)
		flightAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		flightBeforeDeleteMu.Lock()
		flightBeforeDeleteHooks = append(flightBeforeDeleteHooks, flightHook)
		flightBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		flightAfterDeleteMu.Lock()
		flightAfterDeleteHooks = append(flightAfterDeleteHooks, flightHook)
		flightAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		flightBeforeUpsertMu.Lock()
		flightBeforeUpsertHooks = append(flightBeforeUpsertHooks, flightHook)
		flightBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		flightAfterUpsertMu.Lock()
		flightAfterUpsertHooks = append(flightAfterUpsertHooks, flightHook)
		flightAfterUpsertMu.Unlock()
	}
}

// One returns a single flight record from the query.
func (q flightQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Flight, error) {
	o := &Flight{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: failed to execute a one query for flights")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Flight records from the query.
func (q flightQuery) All(ctx context.Context, exec boil.ContextExecutor) (FlightSlice, error) {
	var o []*Flight

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbmodels: failed to assign all query results to Flight slice")
	}

	if len(flightAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Flight records in the query.
func (q flightQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to count flights rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q flightQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: failed to check if flights exists")
	}

	return count > 0, nil
}

// Flights retrieves all the records using an executor.
func Flights(mods ...qm.QueryMod) flightQuery {
	mods = append(mods, qm.From("\"flights\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"flights\".*"})
	}

	return flightQuery{q}
}

// FindFlight retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindFlight(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*Flight, error) {
	flightObj := &Flight{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"flights\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, flightObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: unable to select from flights")
	}

	if err = flightObj.doAfterSelectHooks(ctx, exec); err != nil {
		return flightObj, err
	}

	return flightObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Flight) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodels: no flights provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(flightColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	flightInsertCacheMut.RLock()
	cache, cached := flightInsertCache[key]
	flightInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			flightAllColumns,
			flightColumnsWithDefault,
			flightColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(flightType, flightMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(flightType, flightMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"flights\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"flights\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to insert into flights")
	}

	if !cached {
		flightInsertCacheMut.Lock()
		flightInsertCache[key] = cache
		flightInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Flight.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Flight) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	flightUpdateCacheMut.RLock()
	cache, cached := flightUpdateCache[key]
	flightUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			flightAllColumns,
			flightPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbmodels: unable to update flights, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"flights\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, flightPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(flightType, flightMapping, append(wl, flightPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update flights row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by update for flights")
	}

	if !cached {
		flightUpdateCacheMut.Lock()
		flightUpdateCache[key] = cache
		flightUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q flightQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all for flights")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected for flights")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o FlightSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbmodels: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), flightPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"flights\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, flightPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all in flight slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected all in update all flight")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Flight) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbmodels: no flights provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(flightColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	flightUpsertCacheMut.RLock()
	cache, cached := flightUpsertCache[key]
	flightUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			flightAllColumns,
			flightColumnsWithDefault,
			flightColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			flightAllColumns,
			flightPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbmodels: unable to upsert flights, could not build update column list")
		}

		ret := strmangle.SetComplement(flightAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(flightPrimaryKeyColumns) == 0 {
				return errors.New("dbmodels: unable to upsert flights, could not build conflict column list")
			}

			conflict = make([]string, len(flightPrimaryKeyColumns))
			copy(conflict, flightPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"flights\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(flightType, flightMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(flightType, flightMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to upsert flights")
	}

	if !cached {
		flightUpsertCacheMut.Lock()
		flightUpsertCache[key] = cache
		flightUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Flight record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Flight) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbmodels: no Flight provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), flightPrimaryKeyMapping)
	sql := "DELETE FROM \"flights\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete from flights")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by delete for flights")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q flightQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbmodels: no flightQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from flights")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for flights")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o FlightSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(flightBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), flightPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"flights\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, flightPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from flight slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for flights")
	}

	if len(flightAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Flight) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindFlight(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *FlightSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := FlightSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), flightPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"flights\".* FROM \"flights\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, flightPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to reload all in FlightSlice")
	}

	*o = slice

	return nil
}

// FlightExists checks if the Flight row exists.
func FlightExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"flights\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: unable to check if flights exists")
	}

	return exists, nil
}

// Exists checks if the Flight row exists.
func (o *Flight) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return FlightExists(ctx, exec, o.ID)
}
