// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Overpayment is an object representing the database table.
type Overpayment struct {
	ID              string        `boil:"id" json:"id" toml:"id" yaml:"id"`
	AccountID       string        `boil:"account_id" json:"account_id" toml:"account_id" yaml:"account_id"`
	ProductID       string        `boil:"product_id" json:"product_id" toml:"product_id" yaml:"product_id"`
	PaymentID       string        `boil:"payment_id" json:"payment_id" toml:"payment_id" yaml:"payment_id"`
	OverpaymentType null.String   `boil:"overpayment_type" json:"overpayment_type,omitempty" toml:"overpayment_type" yaml:"overpayment_type,omitempty"`
	Amount          types.Decimal `boil:"amount" json:"amount" toml:"amount" yaml:"amount"`
	PenaltyAmount   types.Decimal `boil:"penalty_amount" json:"penalty_amount" toml:"penalty_amount" yaml:"penalty_amount"`
	InterestSaved   types.Decimal `boil:"interest_saved" json:"interest_saved" toml:"interest_saved" yaml:"interest_saved"`
	NewTermMonths   null.Int      `boil:"new_term_months" json:"new_term_months,omitempty" toml:"new_term_months" yaml:"new_term_months,omitempty"`
	CalculationDate null.Time     `boil:"calculation_date" json:"calculation_date,omitempty" toml:"calculation_date" yaml:"calculation_date,omitempty"`
	EffectiveDate   null.Time     `boil:"effective_date" json:"effective_date,omitempty" toml:"effective_date" yaml:"effective_date,omitempty"`
	Status          null.String   `boil:"status" json:"status,omitempty" toml:"status" yaml:"status,omitempty"`
	CreatedBy       null.String   `boil:"created_by" json:"created_by,omitempty" toml:"created_by" yaml:"created_by,omitempty"`
	CreatedAt       null.Time     `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`

	R *overpaymentR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L overpaymentL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var OverpaymentColumns = struct {
	ID              string
	AccountID       string
	ProductID       string
	PaymentID       string
	OverpaymentType string
	Amount          string
	PenaltyAmount   string
	InterestSaved   string
	NewTermMonths   string
	CalculationDate string
	EffectiveDate   string
	Status          string
	CreatedBy       string
	CreatedAt       string
}{
	ID:              "id",
	AccountID:       "account_id",
	ProductID:       "product_id",
	PaymentID:       "payment_id",
	OverpaymentType: "overpayment_type",
	Amount:          "amount",
	PenaltyAmount:   "penalty_amount",
	InterestSaved:   "interest_saved",
	NewTermMonths:   "new_term_months",
	CalculationDate: "calculation_date",
	EffectiveDate:   "effective_date",
	Status:          "status",
	CreatedBy:       "created_by",
	CreatedAt:       "created_at",
}

var OverpaymentTableColumns = struct {
	ID              string
	AccountID       string
	ProductID       string
	PaymentID       string
	OverpaymentType string
	Amount          string
	PenaltyAmount   string
	InterestSaved   string
	NewTermMonths   string
	CalculationDate string
	EffectiveDate   string
	Status          string
	CreatedBy       string
	CreatedAt       string
}{
	ID:              "overpayments.id",
	AccountID:       "overpayments.account_id",
	ProductID:       "overpayments.product_id",
	PaymentID:       "overpayments.payment_id",
	OverpaymentType: "overpayments.overpayment_type",
	Amount:          "overpayments.amount",
	PenaltyAmount:   "overpayments.penalty_amount",
	InterestSaved:   "overpayments.interest_saved",
	NewTermMonths:   "overpayments.new_term_months",
	CalculationDate: "overpayments.calculation_date",
	EffectiveDate:   "overpayments.effective_date",
	Status:          "overpayments.status",
	CreatedBy:       "overpayments.created_by",
	CreatedAt:       "overpayments.created_at",
}

// Generated where

var OverpaymentWhere = struct {
	ID              whereHelperstring
	AccountID       whereHelperstring
	ProductID       whereHelperstring
	PaymentID       whereHelperstring
	OverpaymentType whereHelpernull_String
	Amount          whereHelpertypes_Decimal
	PenaltyAmount   whereHelpertypes_Decimal
	InterestSaved   whereHelpertypes_Decimal
	NewTermMonths   whereHelpernull_Int
	CalculationDate whereHelpernull_Time
	EffectiveDate   whereHelpernull_Time
	Status          whereHelpernull_String
	CreatedBy       whereHelpernull_String
	CreatedAt       whereHelpernull_Time
}{
	ID:              whereHelperstring{field: "\"overpayments\".\"id\""},
	AccountID:       whereHelperstring{field: "\"overpayments\".\"account_id\""},
	ProductID:       whereHelperstring{field: "\"overpayments\".\"product_id\""},
	PaymentID:       whereHelperstring{field: "\"overpayments\".\"payment_id\""},
	OverpaymentType: whereHelpernull_String{field: "\"overpayments\".\"overpayment_type\""},
	Amount:          whereHelpertypes_Decimal{field: "\"overpayments\".\"amount\""},
	PenaltyAmount:   whereHelpertypes_Decimal{field: "\"overpayments\".\"penalty_amount\""},
	InterestSaved:   whereHelpertypes_Decimal{field: "\"overpayments\".\"interest_saved\""},
	NewTermMonths:   whereHelpernull_Int{field: "\"overpayments\".\"new_term_months\""},
	CalculationDate: whereHelpernull_Time{field: "\"overpayments\".\"calculation_date\""},
	EffectiveDate:   whereHelpernull_Time{field: "\"overpayments\".\"effective_date\""},
	Status:          whereHelpernull_String{field: "\"overpayments\".\"status\""},
	CreatedBy:       whereHelpernull_String{field: "\"overpayments\".\"created_by\""},
	CreatedAt:       whereHelpernull_Time{field: "\"overpayments\".\"created_at\""},
}

// OverpaymentRels is where relationship names are stored.
var OverpaymentRels = struct {
	Account string
	Payment string
	Product string
}{
	Account: "Account",
	Payment: "Payment",
	Product: "Product",
}

// overpaymentR is where relationships are stored.
type overpaymentR struct {
	Account *Account `boil:"Account" json:"Account" toml:"Account" yaml:"Account"`
	Payment *Payment `boil:"Payment" json:"Payment" toml:"Payment" yaml:"Payment"`
	Product *Product `boil:"Product" json:"Product" toml:"Product" yaml:"Product"`
}

// NewStruct creates a new relationship struct
func (*overpaymentR) NewStruct() *overpaymentR {
	return &overpaymentR{}
}

func (o *Overpayment) GetAccount() *Account {
	if o == nil {
		return nil
	}

	return o.R.GetAccount()
}

func (r *overpaymentR) GetAccount() *Account {
	if r == nil {
		return nil
	}

	return r.Account
}

func (o *Overpayment) GetPayment() *Payment {
	if o == nil {
		return nil
	}

	return o.R.GetPayment()
}

func (r *overpaymentR) GetPayment() *Payment {
	if r == nil {
		return nil
	}

	return r.Payment
}

func (o *Overpayment) GetProduct() *Product {
	if o == nil {
		return nil
	}

	return o.R.GetProduct()
}

func (r *overpaymentR) GetProduct() *Product {
	if r == nil {
		return nil
	}

	return r.Product
}

// overpaymentL is where Load methods for each relationship are stored.
type overpaymentL struct{}

var (
	overpaymentAllColumns            = []string{"id", "account_id", "product_id", "payment_id", "overpayment_type", "amount", "penalty_amount", "interest_saved", "new_term_months", "calculation_date", "effective_date", "status", "created_by", "created_at"}
	overpaymentColumnsWithoutDefault = []string{"id", "account_id", "product_id", "payment_id", "amount"}
	overpaymentColumnsWithDefault    = []string{"overpayment_type", "penalty_amount", "interest_saved", "new_term_months", "calculation_date", "effective_date", "status", "created_by", "created_at"}
	overpaymentPrimaryKeyColumns     = []string{"id"}
	overpaymentGeneratedColumns      = []string{}
)

type (
	// OverpaymentSlice is an alias for a slice of pointers to Overpayment.
	// This should almost always be used instead of []Overpayment.
	OverpaymentSlice []*Overpayment
	// OverpaymentHook is the signature for custom Overpayment hook methods
	OverpaymentHook func(context.Context, boil.ContextExecutor, *Overpayment) error

	overpaymentQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	overpaymentType                 = reflect.TypeOf(&Overpayment{})
	overpaymentMapping              = queries.MakeStructMapping(overpaymentType)
	overpaymentPrimaryKeyMapping, _ = queries.BindMapping(overpaymentType, overpaymentMapping, overpaymentPrimaryKeyColumns)
	overpaymentInsertCacheMut       sync.RWMutex
	overpaymentInsertCache          = make(map[string]insertCache)
	overpaymentUpdateCacheMut       sync.RWMutex
	overpaymentUpdateCache          = make(map[string]updateCache)
	overpaymentUpsertCacheMut       sync.RWMutex
	overpaymentUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var overpaymentAfterSelectMu sync.Mutex
var overpaymentAfterSelectHooks []OverpaymentHook

var overpaymentBeforeInsertMu sync.Mutex
var overpaymentBeforeInsertHooks []OverpaymentHook
var overpaymentAfterInsertMu sync.Mutex
var overpaymentAfterInsertHooks []OverpaymentHook

var overpaymentBeforeUpdateMu sync.Mutex
var overpaymentBeforeUpdateHooks []OverpaymentHook
var overpaymentAfterUpdateMu sync.Mutex
var overpaymentAfterUpdateHooks []OverpaymentHook

var overpaymentBeforeDeleteMu sync.Mutex
var overpaymentBeforeDeleteHooks []OverpaymentHook
var overpaymentAfterDeleteMu sync.Mutex
var overpaymentAfterDeleteHooks []OverpaymentHook

var overpaymentBeforeUpsertMu sync.Mutex
var overpaymentBeforeUpsertHooks []OverpaymentHook
var overpaymentAfterUpsertMu sync.Mutex
var overpaymentAfterUpsertHooks []OverpaymentHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Overpayment) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range overpaymentAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Overpayment) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range overpaymentBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Overpayment) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range overpaymentAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Overpayment) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range overpaymentBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Overpayment) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range overpaymentAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Overpayment) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range overpaymentBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Overpayment) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range overpaymentAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Overpayment) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range overpaymentBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Overpayment) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range overpaymentAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddOverpaymentHook registers your hook function for all future operations.
func AddOverpaymentHook(hookPoint boil.HookPoint, overpaymentHook OverpaymentHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		overpaymentAfterSelectMu.Lock()
		overpaymentAfterSelectHooks = append(overpaymentAfterSelectHooks, overpaymentHook)
		overpaymentAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		overpaymentBeforeInsertMu.Lock()
		overpaymentBeforeInsertHooks = append(overpaymentBeforeInsertHooks, overpaymentHook)
		overpaymentBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		overpaymentAfterInsertMu.Lock()
		overpaymentAfterInsertHooks = append(overpaymentAfterInsertHooks, overpaymentHook)
		overpaymentAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		overpaymentBeforeUpdateMu.Lock()
		overpaymentBeforeUpdateHooks = append(overpaymentBeforeUpdateHooks, overpaymentHook)
		overpaymentBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		overpaymentAfterUpdateMu.Lock()
		overpaymentAfterUpdateHooks = append(overpaymentAfterUpdateHooks, overpaymentHook)
		overpaymentAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		overpaymentBeforeDeleteMu.Lock()
		overpaymentBeforeDeleteHooks = append(overpaymentBeforeDeleteHooks, overpaymentHook)
		overpaymentBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		overpaymentAfterDeleteMu.Lock()
		overpaymentAfterDeleteHooks = append(overpaymentAfterDeleteHooks, overpaymentHook)
		overpaymentAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		overpaymentBeforeUpsertMu.Lock()
		overpaymentBeforeUpsertHooks = append(overpaymentBeforeUpsertHooks, overpaymentHook)
		overpaymentBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		overpaymentAfterUpsertMu.Lock()
		overpaymentAfterUpsertHooks = append(overpaymentAfterUpsertHooks, overpaymentHook)
		overpaymentAfterUpsertMu.Unlock()
	}
}

// One returns a single overpayment record from the query.
func (q overpaymentQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Overpayment, error) {
	o := &Overpayment{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: failed to execute a one query for overpayments")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Overpayment records from the query.
func (q overpaymentQuery) All(ctx context.Context, exec boil.ContextExecutor) (OverpaymentSlice, error) {
	var o []*Overpayment

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbmodels: failed to assign all query results to Overpayment slice")
	}

	if len(overpaymentAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Overpayment records in the query.
func (q overpaymentQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to count overpayments rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q overpaymentQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: failed to check if overpayments exists")
	}

	return count > 0, nil
}

// Account pointed to by the foreign key.
func (o *Overpayment) Account(mods ...qm.QueryMod) accountQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.AccountID),
	}

	queryMods = append(queryMods, mods...)

	return Accounts(queryMods...)
}

// Payment pointed to by the foreign key.
func (o *Overpayment) Payment(mods ...qm.QueryMod) paymentQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.PaymentID),
	}

	queryMods = append(queryMods, mods...)

	return Payments(queryMods...)
}

// Product pointed to by the foreign key.
func (o *Overpayment) Product(mods ...qm.QueryMod) productQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ProductID),
	}

	queryMods = append(queryMods, mods...)

	return Products(queryMods...)
}

// LoadAccount allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (overpaymentL) LoadAccount(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOverpayment interface{}, mods queries.Applicator) error {
	var slice []*Overpayment
	var object *Overpayment

	if singular {
		var ok bool
		object, ok = maybeOverpayment.(*Overpayment)
		if !ok {
			object = new(Overpayment)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeOverpayment)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeOverpayment))
			}
		}
	} else {
		s, ok := maybeOverpayment.(*[]*Overpayment)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeOverpayment)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeOverpayment))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &overpaymentR{}
		}
		args[object.AccountID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &overpaymentR{}
			}

			args[obj.AccountID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`accounts`),
		qm.WhereIn(`accounts.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Account")
	}

	var resultSlice []*Account
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Account")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for accounts")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for accounts")
	}

	if len(accountAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Account = foreign
		if foreign.R == nil {
			foreign.R = &accountR{}
		}
		foreign.R.Overpayments = append(foreign.R.Overpayments, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.AccountID == foreign.ID {
				local.R.Account = foreign
				if foreign.R == nil {
					foreign.R = &accountR{}
				}
				foreign.R.Overpayments = append(foreign.R.Overpayments, local)
				break
			}
		}
	}

	return nil
}

// LoadPayment allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (overpaymentL) LoadPayment(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOverpayment interface{}, mods queries.Applicator) error {
	var slice []*Overpayment
	var object *Overpayment

	if singular {
		var ok bool
		object, ok = maybeOverpayment.(*Overpayment)
		if !ok {
			object = new(Overpayment)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeOverpayment)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeOverpayment))
			}
		}
	} else {
		s, ok := maybeOverpayment.(*[]*Overpayment)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeOverpayment)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeOverpayment))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &overpaymentR{}
		}
		args[object.PaymentID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &overpaymentR{}
			}

			args[obj.PaymentID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`payments`),
		qm.WhereIn(`payments.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Payment")
	}

	var resultSlice []*Payment
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Payment")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for payments")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for payments")
	}

	if len(paymentAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Payment = foreign
		if foreign.R == nil {
			foreign.R = &paymentR{}
		}
		foreign.R.Overpayments = append(foreign.R.Overpayments, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.PaymentID == foreign.ID {
				local.R.Payment = foreign
				if foreign.R == nil {
					foreign.R = &paymentR{}
				}
				foreign.R.Overpayments = append(foreign.R.Overpayments, local)
				break
			}
		}
	}

	return nil
}

// LoadProduct allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (overpaymentL) LoadProduct(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOverpayment interface{}, mods queries.Applicator) error {
	var slice []*Overpayment
	var object *Overpayment

	if singular {
		var ok bool
		object, ok = maybeOverpayment.(*Overpayment)
		if !ok {
			object = new(Overpayment)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeOverpayment)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeOverpayment))
			}
		}
	} else {
		s, ok := maybeOverpayment.(*[]*Overpayment)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeOverpayment)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeOverpayment))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &overpaymentR{}
		}
		args[object.ProductID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &overpaymentR{}
			}

			args[obj.ProductID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`products`),
		qm.WhereIn(`products.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Product")
	}

	var resultSlice []*Product
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Product")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for products")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for products")
	}

	if len(productAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Product = foreign
		if foreign.R == nil {
			foreign.R = &productR{}
		}
		foreign.R.Overpayments = append(foreign.R.Overpayments, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ProductID == foreign.ID {
				local.R.Product = foreign
				if foreign.R == nil {
					foreign.R = &productR{}
				}
				foreign.R.Overpayments = append(foreign.R.Overpayments, local)
				break
			}
		}
	}

	return nil
}

// SetAccount of the overpayment to the related item.
// Sets o.R.Account to related.
// Adds o to related.R.Overpayments.
func (o *Overpayment) SetAccount(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Account) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"overpayments\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"account_id"}),
		strmangle.WhereClause("\"", "\"", 2, overpaymentPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.AccountID = related.ID
	if o.R == nil {
		o.R = &overpaymentR{
			Account: related,
		}
	} else {
		o.R.Account = related
	}

	if related.R == nil {
		related.R = &accountR{
			Overpayments: OverpaymentSlice{o},
		}
	} else {
		related.R.Overpayments = append(related.R.Overpayments, o)
	}

	return nil
}

// SetPayment of the overpayment to the related item.
// Sets o.R.Payment to related.
// Adds o to related.R.Overpayments.
func (o *Overpayment) SetPayment(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Payment) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"overpayments\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"payment_id"}),
		strmangle.WhereClause("\"", "\"", 2, overpaymentPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.PaymentID = related.ID
	if o.R == nil {
		o.R = &overpaymentR{
			Payment: related,
		}
	} else {
		o.R.Payment = related
	}

	if related.R == nil {
		related.R = &paymentR{
			Overpayments: OverpaymentSlice{o},
		}
	} else {
		related.R.Overpayments = append(related.R.Overpayments, o)
	}

	return nil
}

// SetProduct of the overpayment to the related item.
// Sets o.R.Product to related.
// Adds o to related.R.Overpayments.
func (o *Overpayment) SetProduct(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Product) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"overpayments\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"product_id"}),
		strmangle.WhereClause("\"", "\"", 2, overpaymentPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ProductID = related.ID
	if o.R == nil {
		o.R = &overpaymentR{
			Product: related,
		}
	} else {
		o.R.Product = related
	}

	if related.R == nil {
		related.R = &productR{
			Overpayments: OverpaymentSlice{o},
		}
	} else {
		related.R.Overpayments = append(related.R.Overpayments, o)
	}

	return nil
}

// Overpayments retrieves all the records using an executor.
func Overpayments(mods ...qm.QueryMod) overpaymentQuery {
	mods = append(mods, qm.From("\"overpayments\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"overpayments\".*"})
	}

	return overpaymentQuery{q}
}

// FindOverpayment retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindOverpayment(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Overpayment, error) {
	overpaymentObj := &Overpayment{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"overpayments\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, overpaymentObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: unable to select from overpayments")
	}

	if err = overpaymentObj.doAfterSelectHooks(ctx, exec); err != nil {
		return overpaymentObj, err
	}

	return overpaymentObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Overpayment) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodels: no overpayments provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(overpaymentColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	overpaymentInsertCacheMut.RLock()
	cache, cached := overpaymentInsertCache[key]
	overpaymentInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			overpaymentAllColumns,
			overpaymentColumnsWithDefault,
			overpaymentColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(overpaymentType, overpaymentMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(overpaymentType, overpaymentMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"overpayments\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"overpayments\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to insert into overpayments")
	}

	if !cached {
		overpaymentInsertCacheMut.Lock()
		overpaymentInsertCache[key] = cache
		overpaymentInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Overpayment.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Overpayment) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	overpaymentUpdateCacheMut.RLock()
	cache, cached := overpaymentUpdateCache[key]
	overpaymentUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			overpaymentAllColumns,
			overpaymentPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbmodels: unable to update overpayments, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"overpayments\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, overpaymentPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(overpaymentType, overpaymentMapping, append(wl, overpaymentPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update overpayments row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by update for overpayments")
	}

	if !cached {
		overpaymentUpdateCacheMut.Lock()
		overpaymentUpdateCache[key] = cache
		overpaymentUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q overpaymentQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all for overpayments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected for overpayments")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o OverpaymentSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbmodels: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), overpaymentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"overpayments\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, overpaymentPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all in overpayment slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected all in update all overpayment")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Overpayment) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbmodels: no overpayments provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(overpaymentColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	overpaymentUpsertCacheMut.RLock()
	cache, cached := overpaymentUpsertCache[key]
	overpaymentUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			overpaymentAllColumns,
			overpaymentColumnsWithDefault,
			overpaymentColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			overpaymentAllColumns,
			overpaymentPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbmodels: unable to upsert overpayments, could not build update column list")
		}

		ret := strmangle.SetComplement(overpaymentAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(overpaymentPrimaryKeyColumns) == 0 {
				return errors.New("dbmodels: unable to upsert overpayments, could not build conflict column list")
			}

			conflict = make([]string, len(overpaymentPrimaryKeyColumns))
			copy(conflict, overpaymentPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"overpayments\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(overpaymentType, overpaymentMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(overpaymentType, overpaymentMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to upsert overpayments")
	}

	if !cached {
		overpaymentUpsertCacheMut.Lock()
		overpaymentUpsertCache[key] = cache
		overpaymentUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Overpayment record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Overpayment) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbmodels: no Overpayment provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), overpaymentPrimaryKeyMapping)
	sql := "DELETE FROM \"overpayments\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete from overpayments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by delete for overpayments")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q overpaymentQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbmodels: no overpaymentQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from overpayments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for overpayments")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o OverpaymentSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(overpaymentBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), overpaymentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"overpayments\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, overpaymentPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from overpayment slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for overpayments")
	}

	if len(overpaymentAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Overpayment) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindOverpayment(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *OverpaymentSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := OverpaymentSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), overpaymentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"overpayments\".* FROM \"overpayments\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, overpaymentPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to reload all in OverpaymentSlice")
	}

	*o = slice

	return nil
}

// OverpaymentExists checks if the Overpayment row exists.
func OverpaymentExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"overpayments\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: unable to check if overpayments exists")
	}

	return exists, nil
}

// Exists checks if the Overpayment row exists.
func (o *Overpayment) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return OverpaymentExists(ctx, exec, o.ID)
}
