// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// SearchHistory is an object representing the database table.
type SearchHistory struct {
	ID         string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID     int         `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	Query      string      `boil:"query" json:"query" toml:"query" yaml:"query"`
	EntityType null.String `boil:"entity_type" json:"entity_type,omitempty" toml:"entity_type" yaml:"entity_type,omitempty"`
	CreatedAt  null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt  null.Time   `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	DeletedAt  null.Time   `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *searchHistoryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L searchHistoryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SearchHistoryColumns = struct {
	ID         string
	UserID     string
	Query      string
	EntityType string
	CreatedAt  string
	UpdatedAt  string
	DeletedAt  string
}{
	ID:         "id",
	UserID:     "user_id",
	Query:      "query",
	EntityType: "entity_type",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
	DeletedAt:  "deleted_at",
}

var SearchHistoryTableColumns = struct {
	ID         string
	UserID     string
	Query      string
	EntityType string
	CreatedAt  string
	UpdatedAt  string
	DeletedAt  string
}{
	ID:         "search_history.id",
	UserID:     "search_history.user_id",
	Query:      "search_history.query",
	EntityType: "search_history.entity_type",
	CreatedAt:  "search_history.created_at",
	UpdatedAt:  "search_history.updated_at",
	DeletedAt:  "search_history.deleted_at",
}

// Generated where

var SearchHistoryWhere = struct {
	ID         whereHelperstring
	UserID     whereHelperint
	Query      whereHelperstring
	EntityType whereHelpernull_String
	CreatedAt  whereHelpernull_Time
	UpdatedAt  whereHelpernull_Time
	DeletedAt  whereHelpernull_Time
}{
	ID:         whereHelperstring{field: "\"search_history\".\"id\""},
	UserID:     whereHelperint{field: "\"search_history\".\"user_id\""},
	Query:      whereHelperstring{field: "\"search_history\".\"query\""},
	EntityType: whereHelpernull_String{field: "\"search_history\".\"entity_type\""},
	CreatedAt:  whereHelpernull_Time{field: "\"search_history\".\"created_at\""},
	UpdatedAt:  whereHelpernull_Time{field: "\"search_history\".\"updated_at\""},
	DeletedAt:  whereHelpernull_Time{field: "\"search_history\".\"deleted_at\""},
}

// SearchHistoryRels is where relationship names are stored.
var SearchHistoryRels = struct {
	User string
}{
	User: "User",
}

// searchHistoryR is where relationships are stored.
type searchHistoryR struct {
	User *User `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*searchHistoryR) NewStruct() *searchHistoryR {
	return &searchHistoryR{}
}

func (o *SearchHistory) GetUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUser()
}

func (r *searchHistoryR) GetUser() *User {
	if r == nil {
		return nil
	}

	return r.User
}

// searchHistoryL is where Load methods for each relationship are stored.
type searchHistoryL struct{}

var (
	searchHistoryAllColumns            = []string{"id", "user_id", "query", "entity_type", "created_at", "updated_at", "deleted_at"}
	searchHistoryColumnsWithoutDefault = []string{"id", "user_id", "query"}
	searchHistoryColumnsWithDefault    = []string{"entity_type", "created_at", "updated_at", "deleted_at"}
	searchHistoryPrimaryKeyColumns     = []string{"id"}
	searchHistoryGeneratedColumns      = []string{}
)

type (
	// SearchHistorySlice is an alias for a slice of pointers to SearchHistory.
	// This should almost always be used instead of []SearchHistory.
	SearchHistorySlice []*SearchHistory
	// SearchHistoryHook is the signature for custom SearchHistory hook methods
	SearchHistoryHook func(context.Context, boil.ContextExecutor, *SearchHistory) error

	searchHistoryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	searchHistoryType                 = reflect.TypeOf(&SearchHistory{})
	searchHistoryMapping              = queries.MakeStructMapping(searchHistoryType)
	searchHistoryPrimaryKeyMapping, _ = queries.BindMapping(searchHistoryType, searchHistoryMapping, searchHistoryPrimaryKeyColumns)
	searchHistoryInsertCacheMut       sync.RWMutex
	searchHistoryInsertCache          = make(map[string]insertCache)
	searchHistoryUpdateCacheMut       sync.RWMutex
	searchHistoryUpdateCache          = make(map[string]updateCache)
	searchHistoryUpsertCacheMut       sync.RWMutex
	searchHistoryUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var searchHistoryAfterSelectMu sync.Mutex
var searchHistoryAfterSelectHooks []SearchHistoryHook

var searchHistoryBeforeInsertMu sync.Mutex
var searchHistoryBeforeInsertHooks []SearchHistoryHook
var searchHistoryAfterInsertMu sync.Mutex
var searchHistoryAfterInsertHooks []SearchHistoryHook

var searchHistoryBeforeUpdateMu sync.Mutex
var searchHistoryBeforeUpdateHooks []SearchHistoryHook
var searchHistoryAfterUpdateMu sync.Mutex
var searchHistoryAfterUpdateHooks []SearchHistoryHook

var searchHistoryBeforeDeleteMu sync.Mutex
var searchHistoryBeforeDeleteHooks []SearchHistoryHook
var searchHistoryAfterDeleteMu sync.Mutex
var searchHistoryAfterDeleteHooks []SearchHistoryHook

var searchHistoryBeforeUpsertMu sync.Mutex
var searchHistoryBeforeUpsertHooks []SearchHistoryHook
var searchHistoryAfterUpsertMu sync.Mutex
var searchHistoryAfterUpsertHooks []SearchHistoryHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *SearchHistory) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchHistoryAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *SearchHistory) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchHistoryBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *SearchHistory) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchHistoryAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *SearchHistory) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchHistoryBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *SearchHistory) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchHistoryAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *SearchHistory) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchHistoryBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *SearchHistory) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchHistoryAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *SearchHistory) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchHistoryBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *SearchHistory) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchHistoryAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSearchHistoryHook registers your hook function for all future operations.
func AddSearchHistoryHook(hookPoint boil.HookPoint, searchHistoryHook SearchHistoryHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		searchHistoryAfterSelectMu.Lock()
		searchHistoryAfterSelectHooks = append(searchHistoryAfterSelectHooks, searchHistoryHook)
		searchHistoryAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		searchHistoryBeforeInsertMu.Lock()
		searchHistoryBeforeInsertHooks = append(searchHistoryBeforeInsertHooks, searchHistoryHook)
		searchHistoryBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		searchHistoryAfterInsertMu.Lock()
		searchHistoryAfterInsertHooks = append(searchHistoryAfterInsertHooks, searchHistoryHook)
		searchHistoryAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		searchHistoryBeforeUpdateMu.Lock()
		searchHistoryBeforeUpdateHooks = append(searchHistoryBeforeUpdateHooks, searchHistoryHook)
		searchHistoryBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		searchHistoryAfterUpdateMu.Lock()
		searchHistoryAfterUpdateHooks = append(searchHistoryAfterUpdateHooks, searchHistoryHook)
		searchHistoryAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		searchHistoryBeforeDeleteMu.Lock()
		searchHistoryBeforeDeleteHooks = append(searchHistoryBeforeDeleteHooks, searchHistoryHook)
		searchHistoryBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		searchHistoryAfterDeleteMu.Lock()
		searchHistoryAfterDeleteHooks = append(searchHistoryAfterDeleteHooks, searchHistoryHook)
		searchHistoryAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		searchHistoryBeforeUpsertMu.Lock()
		searchHistoryBeforeUpsertHooks = append(searchHistoryBeforeUpsertHooks, searchHistoryHook)
		searchHistoryBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		searchHistoryAfterUpsertMu.Lock()
		searchHistoryAfterUpsertHooks = append(searchHistoryAfterUpsertHooks, searchHistoryHook)
		searchHistoryAfterUpsertMu.Unlock()
	}
}

// One returns a single searchHistory record from the query.
func (q searchHistoryQuery) One(ctx context.Context, exec boil.ContextExecutor) (*SearchHistory, error) {
	o := &SearchHistory{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: failed to execute a one query for search_history")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all SearchHistory records from the query.
func (q searchHistoryQuery) All(ctx context.Context, exec boil.ContextExecutor) (SearchHistorySlice, error) {
	var o []*SearchHistory

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbmodels: failed to assign all query results to SearchHistory slice")
	}

	if len(searchHistoryAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all SearchHistory records in the query.
func (q searchHistoryQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to count search_history rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q searchHistoryQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: failed to check if search_history exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *SearchHistory) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (searchHistoryL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSearchHistory interface{}, mods queries.Applicator) error {
	var slice []*SearchHistory
	var object *SearchHistory

	if singular {
		var ok bool
		object, ok = maybeSearchHistory.(*SearchHistory)
		if !ok {
			object = new(SearchHistory)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSearchHistory)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSearchHistory))
			}
		}
	} else {
		s, ok := maybeSearchHistory.(*[]*SearchHistory)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSearchHistory)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSearchHistory))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &searchHistoryR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &searchHistoryR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.SearchHistories = append(foreign.R.SearchHistories, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.SearchHistories = append(foreign.R.SearchHistories, local)
				break
			}
		}
	}

	return nil
}

// SetUser of the searchHistory to the related item.
// Sets o.R.User to related.
// Adds o to related.R.SearchHistories.
func (o *SearchHistory) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"search_history\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, searchHistoryPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &searchHistoryR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			SearchHistories: SearchHistorySlice{o},
		}
	} else {
		related.R.SearchHistories = append(related.R.SearchHistories, o)
	}

	return nil
}

// SearchHistories retrieves all the records using an executor.
func SearchHistories(mods ...qm.QueryMod) searchHistoryQuery {
	mods = append(mods, qm.From("\"search_history\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"search_history\".*"})
	}

	return searchHistoryQuery{q}
}

// FindSearchHistory retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSearchHistory(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*SearchHistory, error) {
	searchHistoryObj := &SearchHistory{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"search_history\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, searchHistoryObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: unable to select from search_history")
	}

	if err = searchHistoryObj.doAfterSelectHooks(ctx, exec); err != nil {
		return searchHistoryObj, err
	}

	return searchHistoryObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SearchHistory) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodels: no search_history provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(searchHistoryColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	searchHistoryInsertCacheMut.RLock()
	cache, cached := searchHistoryInsertCache[key]
	searchHistoryInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			searchHistoryAllColumns,
			searchHistoryColumnsWithDefault,
			searchHistoryColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(searchHistoryType, searchHistoryMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(searchHistoryType, searchHistoryMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"search_history\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"search_history\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to insert into search_history")
	}

	if !cached {
		searchHistoryInsertCacheMut.Lock()
		searchHistoryInsertCache[key] = cache
		searchHistoryInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the SearchHistory.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *SearchHistory) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	searchHistoryUpdateCacheMut.RLock()
	cache, cached := searchHistoryUpdateCache[key]
	searchHistoryUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			searchHistoryAllColumns,
			searchHistoryPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbmodels: unable to update search_history, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"search_history\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, searchHistoryPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(searchHistoryType, searchHistoryMapping, append(wl, searchHistoryPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update search_history row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by update for search_history")
	}

	if !cached {
		searchHistoryUpdateCacheMut.Lock()
		searchHistoryUpdateCache[key] = cache
		searchHistoryUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q searchHistoryQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all for search_history")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected for search_history")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SearchHistorySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbmodels: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), searchHistoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"search_history\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, searchHistoryPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all in searchHistory slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected all in update all searchHistory")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SearchHistory) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbmodels: no search_history provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(searchHistoryColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	searchHistoryUpsertCacheMut.RLock()
	cache, cached := searchHistoryUpsertCache[key]
	searchHistoryUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			searchHistoryAllColumns,
			searchHistoryColumnsWithDefault,
			searchHistoryColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			searchHistoryAllColumns,
			searchHistoryPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbmodels: unable to upsert search_history, could not build update column list")
		}

		ret := strmangle.SetComplement(searchHistoryAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(searchHistoryPrimaryKeyColumns) == 0 {
				return errors.New("dbmodels: unable to upsert search_history, could not build conflict column list")
			}

			conflict = make([]string, len(searchHistoryPrimaryKeyColumns))
			copy(conflict, searchHistoryPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"search_history\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(searchHistoryType, searchHistoryMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(searchHistoryType, searchHistoryMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to upsert search_history")
	}

	if !cached {
		searchHistoryUpsertCacheMut.Lock()
		searchHistoryUpsertCache[key] = cache
		searchHistoryUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single SearchHistory record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SearchHistory) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbmodels: no SearchHistory provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), searchHistoryPrimaryKeyMapping)
	sql := "DELETE FROM \"search_history\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete from search_history")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by delete for search_history")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q searchHistoryQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbmodels: no searchHistoryQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from search_history")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for search_history")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SearchHistorySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(searchHistoryBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), searchHistoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"search_history\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, searchHistoryPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from searchHistory slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for search_history")
	}

	if len(searchHistoryAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SearchHistory) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSearchHistory(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SearchHistorySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SearchHistorySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), searchHistoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"search_history\".* FROM \"search_history\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, searchHistoryPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to reload all in SearchHistorySlice")
	}

	*o = slice

	return nil
}

// SearchHistoryExists checks if the SearchHistory row exists.
func SearchHistoryExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"search_history\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: unable to check if search_history exists")
	}

	return exists, nil
}

// Exists checks if the SearchHistory row exists.
func (o *SearchHistory) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return SearchHistoryExists(ctx, exec, o.ID)
}
