// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// WebQuery is an object representing the database table.
type WebQuery struct {
	ID            int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	FirstName     null.String `boil:"first_name" json:"first_name,omitempty" toml:"first_name" yaml:"first_name,omitempty"`
	Email         null.String `boil:"email" json:"email,omitempty" toml:"email" yaml:"email,omitempty"`
	Phone         null.String `boil:"phone" json:"phone,omitempty" toml:"phone" yaml:"phone,omitempty"`
	Message       null.String `boil:"message" json:"message,omitempty" toml:"message" yaml:"message,omitempty"`
	CreatedAt     time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	Surname       null.String `boil:"surname" json:"surname,omitempty" toml:"surname" yaml:"surname,omitempty"`
	Company       null.String `boil:"company" json:"company,omitempty" toml:"company" yaml:"company,omitempty"`
	StreetAddress null.String `boil:"street_address" json:"street_address,omitempty" toml:"street_address" yaml:"street_address,omitempty"`
	City          null.String `boil:"city" json:"city,omitempty" toml:"city" yaml:"city,omitempty"`
	Zip           null.String `boil:"zip" json:"zip,omitempty" toml:"zip" yaml:"zip,omitempty"`
	ExtraInfo     null.JSON   `boil:"extra_info" json:"extra_info,omitempty" toml:"extra_info" yaml:"extra_info,omitempty"`
	Querytype     null.String `boil:"querytype" json:"querytype,omitempty" toml:"querytype" yaml:"querytype,omitempty"`
	Owner         null.Int    `boil:"owner" json:"owner,omitempty" toml:"owner" yaml:"owner,omitempty"`
	UpdatedAt     null.Time   `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	Status        string      `boil:"status" json:"status" toml:"status" yaml:"status"`

	R *webQueryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L webQueryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WebQueryColumns = struct {
	ID            string
	FirstName     string
	Email         string
	Phone         string
	Message       string
	CreatedAt     string
	Surname       string
	Company       string
	StreetAddress string
	City          string
	Zip           string
	ExtraInfo     string
	Querytype     string
	Owner         string
	UpdatedAt     string
	Status        string
}{
	ID:            "id",
	FirstName:     "first_name",
	Email:         "email",
	Phone:         "phone",
	Message:       "message",
	CreatedAt:     "created_at",
	Surname:       "surname",
	Company:       "company",
	StreetAddress: "street_address",
	City:          "city",
	Zip:           "zip",
	ExtraInfo:     "extra_info",
	Querytype:     "querytype",
	Owner:         "owner",
	UpdatedAt:     "updated_at",
	Status:        "status",
}

var WebQueryTableColumns = struct {
	ID            string
	FirstName     string
	Email         string
	Phone         string
	Message       string
	CreatedAt     string
	Surname       string
	Company       string
	StreetAddress string
	City          string
	Zip           string
	ExtraInfo     string
	Querytype     string
	Owner         string
	UpdatedAt     string
	Status        string
}{
	ID:            "web_query.id",
	FirstName:     "web_query.first_name",
	Email:         "web_query.email",
	Phone:         "web_query.phone",
	Message:       "web_query.message",
	CreatedAt:     "web_query.created_at",
	Surname:       "web_query.surname",
	Company:       "web_query.company",
	StreetAddress: "web_query.street_address",
	City:          "web_query.city",
	Zip:           "web_query.zip",
	ExtraInfo:     "web_query.extra_info",
	Querytype:     "web_query.querytype",
	Owner:         "web_query.owner",
	UpdatedAt:     "web_query.updated_at",
	Status:        "web_query.status",
}

// Generated where

type whereHelpernull_JSON struct{ field string }

func (w whereHelpernull_JSON) EQ(x null.JSON) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_JSON) NEQ(x null.JSON) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_JSON) LT(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_JSON) LTE(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_JSON) GT(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_JSON) GTE(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_JSON) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_JSON) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var WebQueryWhere = struct {
	ID            whereHelperint
	FirstName     whereHelpernull_String
	Email         whereHelpernull_String
	Phone         whereHelpernull_String
	Message       whereHelpernull_String
	CreatedAt     whereHelpertime_Time
	Surname       whereHelpernull_String
	Company       whereHelpernull_String
	StreetAddress whereHelpernull_String
	City          whereHelpernull_String
	Zip           whereHelpernull_String
	ExtraInfo     whereHelpernull_JSON
	Querytype     whereHelpernull_String
	Owner         whereHelpernull_Int
	UpdatedAt     whereHelpernull_Time
	Status        whereHelperstring
}{
	ID:            whereHelperint{field: "\"web_query\".\"id\""},
	FirstName:     whereHelpernull_String{field: "\"web_query\".\"first_name\""},
	Email:         whereHelpernull_String{field: "\"web_query\".\"email\""},
	Phone:         whereHelpernull_String{field: "\"web_query\".\"phone\""},
	Message:       whereHelpernull_String{field: "\"web_query\".\"message\""},
	CreatedAt:     whereHelpertime_Time{field: "\"web_query\".\"created_at\""},
	Surname:       whereHelpernull_String{field: "\"web_query\".\"surname\""},
	Company:       whereHelpernull_String{field: "\"web_query\".\"company\""},
	StreetAddress: whereHelpernull_String{field: "\"web_query\".\"street_address\""},
	City:          whereHelpernull_String{field: "\"web_query\".\"city\""},
	Zip:           whereHelpernull_String{field: "\"web_query\".\"zip\""},
	ExtraInfo:     whereHelpernull_JSON{field: "\"web_query\".\"extra_info\""},
	Querytype:     whereHelpernull_String{field: "\"web_query\".\"querytype\""},
	Owner:         whereHelpernull_Int{field: "\"web_query\".\"owner\""},
	UpdatedAt:     whereHelpernull_Time{field: "\"web_query\".\"updated_at\""},
	Status:        whereHelperstring{field: "\"web_query\".\"status\""},
}

// WebQueryRels is where relationship names are stored.
var WebQueryRels = struct {
	OwnerUser     string
	WebQueryNotes string
}{
	OwnerUser:     "OwnerUser",
	WebQueryNotes: "WebQueryNotes",
}

// webQueryR is where relationships are stored.
type webQueryR struct {
	OwnerUser     *User             `boil:"OwnerUser" json:"OwnerUser" toml:"OwnerUser" yaml:"OwnerUser"`
	WebQueryNotes WebQueryNoteSlice `boil:"WebQueryNotes" json:"WebQueryNotes" toml:"WebQueryNotes" yaml:"WebQueryNotes"`
}

// NewStruct creates a new relationship struct
func (*webQueryR) NewStruct() *webQueryR {
	return &webQueryR{}
}

func (o *WebQuery) GetOwnerUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetOwnerUser()
}

func (r *webQueryR) GetOwnerUser() *User {
	if r == nil {
		return nil
	}

	return r.OwnerUser
}

func (o *WebQuery) GetWebQueryNotes() WebQueryNoteSlice {
	if o == nil {
		return nil
	}

	return o.R.GetWebQueryNotes()
}

func (r *webQueryR) GetWebQueryNotes() WebQueryNoteSlice {
	if r == nil {
		return nil
	}

	return r.WebQueryNotes
}

// webQueryL is where Load methods for each relationship are stored.
type webQueryL struct{}

var (
	webQueryAllColumns            = []string{"id", "first_name", "email", "phone", "message", "created_at", "surname", "company", "street_address", "city", "zip", "extra_info", "querytype", "owner", "updated_at", "status"}
	webQueryColumnsWithoutDefault = []string{"created_at"}
	webQueryColumnsWithDefault    = []string{"id", "first_name", "email", "phone", "message", "surname", "company", "street_address", "city", "zip", "extra_info", "querytype", "owner", "updated_at", "status"}
	webQueryPrimaryKeyColumns     = []string{"id"}
	webQueryGeneratedColumns      = []string{}
)

type (
	// WebQuerySlice is an alias for a slice of pointers to WebQuery.
	// This should almost always be used instead of []WebQuery.
	WebQuerySlice []*WebQuery
	// WebQueryHook is the signature for custom WebQuery hook methods
	WebQueryHook func(context.Context, boil.ContextExecutor, *WebQuery) error

	webQueryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	webQueryType                 = reflect.TypeOf(&WebQuery{})
	webQueryMapping              = queries.MakeStructMapping(webQueryType)
	webQueryPrimaryKeyMapping, _ = queries.BindMapping(webQueryType, webQueryMapping, webQueryPrimaryKeyColumns)
	webQueryInsertCacheMut       sync.RWMutex
	webQueryInsertCache          = make(map[string]insertCache)
	webQueryUpdateCacheMut       sync.RWMutex
	webQueryUpdateCache          = make(map[string]updateCache)
	webQueryUpsertCacheMut       sync.RWMutex
	webQueryUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var webQueryAfterSelectMu sync.Mutex
var webQueryAfterSelectHooks []WebQueryHook

var webQueryBeforeInsertMu sync.Mutex
var webQueryBeforeInsertHooks []WebQueryHook
var webQueryAfterInsertMu sync.Mutex
var webQueryAfterInsertHooks []WebQueryHook

var webQueryBeforeUpdateMu sync.Mutex
var webQueryBeforeUpdateHooks []WebQueryHook
var webQueryAfterUpdateMu sync.Mutex
var webQueryAfterUpdateHooks []WebQueryHook

var webQueryBeforeDeleteMu sync.Mutex
var webQueryBeforeDeleteHooks []WebQueryHook
var webQueryAfterDeleteMu sync.Mutex
var webQueryAfterDeleteHooks []WebQueryHook

var webQueryBeforeUpsertMu sync.Mutex
var webQueryBeforeUpsertHooks []WebQueryHook
var webQueryAfterUpsertMu sync.Mutex
var webQueryAfterUpsertHooks []WebQueryHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *WebQuery) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range webQueryAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *WebQuery) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range webQueryBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *WebQuery) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range webQueryAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *WebQuery) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range webQueryBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *WebQuery) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range webQueryAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *WebQuery) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range webQueryBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *WebQuery) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range webQueryAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *WebQuery) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range webQueryBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *WebQuery) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range webQueryAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddWebQueryHook registers your hook function for all future operations.
func AddWebQueryHook(hookPoint boil.HookPoint, webQueryHook WebQueryHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		webQueryAfterSelectMu.Lock()
		webQueryAfterSelectHooks = append(webQueryAfterSelectHooks, webQueryHook)
		webQueryAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		webQueryBeforeInsertMu.Lock()
		webQueryBeforeInsertHooks = append(webQueryBeforeInsertHooks, webQueryHook)
		webQueryBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		webQueryAfterInsertMu.Lock()
		webQueryAfterInsertHooks = append(webQueryAfterInsertHooks, webQueryHook)
		webQueryAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		webQueryBeforeUpdateMu.Lock()
		webQueryBeforeUpdateHooks = append(webQueryBeforeUpdateHooks, webQueryHook)
		webQueryBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		webQueryAfterUpdateMu.Lock()
		webQueryAfterUpdateHooks = append(webQueryAfterUpdateHooks, webQueryHook)
		webQueryAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		webQueryBeforeDeleteMu.Lock()
		webQueryBeforeDeleteHooks = append(webQueryBeforeDeleteHooks, webQueryHook)
		webQueryBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		webQueryAfterDeleteMu.Lock()
		webQueryAfterDeleteHooks = append(webQueryAfterDeleteHooks, webQueryHook)
		webQueryAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		webQueryBeforeUpsertMu.Lock()
		webQueryBeforeUpsertHooks = append(webQueryBeforeUpsertHooks, webQueryHook)
		webQueryBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		webQueryAfterUpsertMu.Lock()
		webQueryAfterUpsertHooks = append(webQueryAfterUpsertHooks, webQueryHook)
		webQueryAfterUpsertMu.Unlock()
	}
}

// One returns a single webQuery record from the query.
func (q webQueryQuery) One(ctx context.Context, exec boil.ContextExecutor) (*WebQuery, error) {
	o := &WebQuery{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: failed to execute a one query for web_query")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all WebQuery records from the query.
func (q webQueryQuery) All(ctx context.Context, exec boil.ContextExecutor) (WebQuerySlice, error) {
	var o []*WebQuery

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbmodels: failed to assign all query results to WebQuery slice")
	}

	if len(webQueryAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all WebQuery records in the query.
func (q webQueryQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to count web_query rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q webQueryQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: failed to check if web_query exists")
	}

	return count > 0, nil
}

// OwnerUser pointed to by the foreign key.
func (o *WebQuery) OwnerUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.Owner),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// WebQueryNotes retrieves all the web_query_note's WebQueryNotes with an executor.
func (o *WebQuery) WebQueryNotes(mods ...qm.QueryMod) webQueryNoteQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"web_query_notes\".\"web_query_id\"=?", o.ID),
	)

	return WebQueryNotes(queryMods...)
}

// LoadOwnerUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (webQueryL) LoadOwnerUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWebQuery interface{}, mods queries.Applicator) error {
	var slice []*WebQuery
	var object *WebQuery

	if singular {
		var ok bool
		object, ok = maybeWebQuery.(*WebQuery)
		if !ok {
			object = new(WebQuery)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWebQuery)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWebQuery))
			}
		}
	} else {
		s, ok := maybeWebQuery.(*[]*WebQuery)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWebQuery)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWebQuery))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &webQueryR{}
		}
		if !queries.IsNil(object.Owner) {
			args[object.Owner] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &webQueryR{}
			}

			if !queries.IsNil(obj.Owner) {
				args[obj.Owner] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.OwnerUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.OwnerWebQueries = append(foreign.R.OwnerWebQueries, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.Owner, foreign.ID) {
				local.R.OwnerUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.OwnerWebQueries = append(foreign.R.OwnerWebQueries, local)
				break
			}
		}
	}

	return nil
}

// LoadWebQueryNotes allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (webQueryL) LoadWebQueryNotes(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWebQuery interface{}, mods queries.Applicator) error {
	var slice []*WebQuery
	var object *WebQuery

	if singular {
		var ok bool
		object, ok = maybeWebQuery.(*WebQuery)
		if !ok {
			object = new(WebQuery)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWebQuery)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWebQuery))
			}
		}
	} else {
		s, ok := maybeWebQuery.(*[]*WebQuery)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWebQuery)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWebQuery))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &webQueryR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &webQueryR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`web_query_notes`),
		qm.WhereIn(`web_query_notes.web_query_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load web_query_notes")
	}

	var resultSlice []*WebQueryNote
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice web_query_notes")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on web_query_notes")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for web_query_notes")
	}

	if len(webQueryNoteAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.WebQueryNotes = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &webQueryNoteR{}
			}
			foreign.R.WebQuery = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.WebQueryID {
				local.R.WebQueryNotes = append(local.R.WebQueryNotes, foreign)
				if foreign.R == nil {
					foreign.R = &webQueryNoteR{}
				}
				foreign.R.WebQuery = local
				break
			}
		}
	}

	return nil
}

// SetOwnerUser of the webQuery to the related item.
// Sets o.R.OwnerUser to related.
// Adds o to related.R.OwnerWebQueries.
func (o *WebQuery) SetOwnerUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"web_query\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"owner"}),
		strmangle.WhereClause("\"", "\"", 2, webQueryPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.Owner, related.ID)
	if o.R == nil {
		o.R = &webQueryR{
			OwnerUser: related,
		}
	} else {
		o.R.OwnerUser = related
	}

	if related.R == nil {
		related.R = &userR{
			OwnerWebQueries: WebQuerySlice{o},
		}
	} else {
		related.R.OwnerWebQueries = append(related.R.OwnerWebQueries, o)
	}

	return nil
}

// RemoveOwnerUser relationship.
// Sets o.R.OwnerUser to nil.
// Removes o from all passed in related items' relationships struct.
func (o *WebQuery) RemoveOwnerUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.Owner, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("owner")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.OwnerUser = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.OwnerWebQueries {
		if queries.Equal(o.Owner, ri.Owner) {
			continue
		}

		ln := len(related.R.OwnerWebQueries)
		if ln > 1 && i < ln-1 {
			related.R.OwnerWebQueries[i] = related.R.OwnerWebQueries[ln-1]
		}
		related.R.OwnerWebQueries = related.R.OwnerWebQueries[:ln-1]
		break
	}
	return nil
}

// AddWebQueryNotes adds the given related objects to the existing relationships
// of the web_query, optionally inserting them as new records.
// Appends related to o.R.WebQueryNotes.
// Sets related.R.WebQuery appropriately.
func (o *WebQuery) AddWebQueryNotes(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*WebQueryNote) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.WebQueryID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"web_query_notes\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"web_query_id"}),
				strmangle.WhereClause("\"", "\"", 2, webQueryNotePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.WebQueryID = o.ID
		}
	}

	if o.R == nil {
		o.R = &webQueryR{
			WebQueryNotes: related,
		}
	} else {
		o.R.WebQueryNotes = append(o.R.WebQueryNotes, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &webQueryNoteR{
				WebQuery: o,
			}
		} else {
			rel.R.WebQuery = o
		}
	}
	return nil
}

// WebQueries retrieves all the records using an executor.
func WebQueries(mods ...qm.QueryMod) webQueryQuery {
	mods = append(mods, qm.From("\"web_query\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"web_query\".*"})
	}

	return webQueryQuery{q}
}

// FindWebQuery retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWebQuery(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*WebQuery, error) {
	webQueryObj := &WebQuery{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"web_query\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, webQueryObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: unable to select from web_query")
	}

	if err = webQueryObj.doAfterSelectHooks(ctx, exec); err != nil {
		return webQueryObj, err
	}

	return webQueryObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *WebQuery) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodels: no web_query provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(webQueryColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	webQueryInsertCacheMut.RLock()
	cache, cached := webQueryInsertCache[key]
	webQueryInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			webQueryAllColumns,
			webQueryColumnsWithDefault,
			webQueryColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(webQueryType, webQueryMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(webQueryType, webQueryMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"web_query\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"web_query\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to insert into web_query")
	}

	if !cached {
		webQueryInsertCacheMut.Lock()
		webQueryInsertCache[key] = cache
		webQueryInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the WebQuery.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *WebQuery) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	webQueryUpdateCacheMut.RLock()
	cache, cached := webQueryUpdateCache[key]
	webQueryUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			webQueryAllColumns,
			webQueryPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbmodels: unable to update web_query, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"web_query\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, webQueryPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(webQueryType, webQueryMapping, append(wl, webQueryPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update web_query row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by update for web_query")
	}

	if !cached {
		webQueryUpdateCacheMut.Lock()
		webQueryUpdateCache[key] = cache
		webQueryUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q webQueryQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all for web_query")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected for web_query")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WebQuerySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbmodels: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), webQueryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"web_query\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, webQueryPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all in webQuery slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected all in update all webQuery")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *WebQuery) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbmodels: no web_query provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(webQueryColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	webQueryUpsertCacheMut.RLock()
	cache, cached := webQueryUpsertCache[key]
	webQueryUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			webQueryAllColumns,
			webQueryColumnsWithDefault,
			webQueryColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			webQueryAllColumns,
			webQueryPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbmodels: unable to upsert web_query, could not build update column list")
		}

		ret := strmangle.SetComplement(webQueryAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(webQueryPrimaryKeyColumns) == 0 {
				return errors.New("dbmodels: unable to upsert web_query, could not build conflict column list")
			}

			conflict = make([]string, len(webQueryPrimaryKeyColumns))
			copy(conflict, webQueryPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"web_query\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(webQueryType, webQueryMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(webQueryType, webQueryMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to upsert web_query")
	}

	if !cached {
		webQueryUpsertCacheMut.Lock()
		webQueryUpsertCache[key] = cache
		webQueryUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single WebQuery record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *WebQuery) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbmodels: no WebQuery provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), webQueryPrimaryKeyMapping)
	sql := "DELETE FROM \"web_query\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete from web_query")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by delete for web_query")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q webQueryQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbmodels: no webQueryQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from web_query")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for web_query")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WebQuerySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(webQueryBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), webQueryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"web_query\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, webQueryPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from webQuery slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for web_query")
	}

	if len(webQueryAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *WebQuery) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWebQuery(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WebQuerySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WebQuerySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), webQueryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"web_query\".* FROM \"web_query\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, webQueryPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to reload all in WebQuerySlice")
	}

	*o = slice

	return nil
}

// WebQueryExists checks if the WebQuery row exists.
func WebQueryExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"web_query\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: unable to check if web_query exists")
	}

	return exists, nil
}

// Exists checks if the WebQuery row exists.
func (o *WebQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WebQueryExists(ctx, exec, o.ID)
}
